"""
build123d_gui.py
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
Build123d Ã— LLM ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰
ã‚¤ãƒ³ãƒãƒ¼ãƒˆã—ã¦ display_dashboard() ã‚’å‘¼ã¶ã ã‘ã§å®Œå…¨ãªGUIãŒè¡¨ç¤ºã•ã‚Œã¾ã™ã€‚

ä½¿ã„æ–¹:
    import build123d_gui
    build123d_gui.display_dashboard()
"""

import sys, os, ast, re, textwrap, traceback, subprocess, importlib

import ipywidgets as w
from IPython.display import display, HTML, clear_output


os.makedirs('output', exist_ok=True)


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# ä¾å­˜ãƒ©ã‚¤ãƒ–ãƒ©ãƒªã®è‡ªå‹•ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
def _ensure_deps():
    pkgs = {
        'ipywidgets': 'ipywidgets',
        'anthropic':  'anthropic',
        'openai':     'openai',
        'google.genai': 'google-genai',
    }
    needs_restart = False
    for mod, pkg in pkgs.items():
        try:
            importlib.import_module(mod)
        except ImportError:
            subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', pkg], check=True)
            needs_restart = True

    if needs_restart:
        try:
            from google.colab import runtime
            print('ğŸ”„ ãƒ©ã‚¤ãƒ–ãƒ©ãƒªã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã—ãŸã€‚ãƒ©ãƒ³ã‚¿ã‚¤ãƒ ã‚’å†èµ·å‹•ã—ã¾ã™...')
            print('   å†èµ·å‹•å¾Œã€ã“ã®ã‚»ãƒ«ã‚’ã‚‚ã†ä¸€åº¦å®Ÿè¡Œã—ã¦ãã ã•ã„ã€‚')
            runtime.unassign()
        except ImportError:
            print('âœ… ãƒ©ã‚¤ãƒ–ãƒ©ãƒªã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«å®Œäº†ï¼ˆãƒ­ãƒ¼ã‚«ãƒ«ç’°å¢ƒï¼‰')

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# çŠ¶æ…‹ç®¡ç†
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
state = dict(
    llm_mode        = 'manual',
    provider        = 'google',
    anthropic_key   = '',
    openai_key      = '',
    google_key      = '',
    anthropic_model = 'claude-opus-4-6',
    openai_model    = 'gpt-4o',
    google_model    = 'gemini-2.5-flash',
    history         = [],
    last_code       = '',
    last_err        = '',
    last_raw        = '',
)

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# ã‚·ã‚¹ãƒ†ãƒ ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆ
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
SYSTEM_PROMPT = textwrap.dedent("""\
    ã‚ãªãŸã¯Build123dã®ã‚¨ã‚­ã‚¹ãƒ‘ãƒ¼ãƒˆã§ã™ã€‚ä»¥ä¸‹ã®ãƒ«ãƒ¼ãƒ«ã«å¾“ã£ã¦Pythonã‚³ãƒ¼ãƒ‰ã‚’ç”Ÿæˆã—ã¦ãã ã•ã„ã€‚

    ã€ãƒ«ãƒ¼ãƒ«ã€‘
    1. å¿…ãš `from build123d import *` ã§ã‚¤ãƒ³ãƒãƒ¼ãƒˆã™ã‚‹
    2. å½¢çŠ¶ã¯ `with BuildPart() as part:` ã®ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆãƒãƒãƒ¼ã‚¸ãƒ£å†…ã«æ›¸ã
    3. å¯¸æ³•ã¯ã™ã¹ã¦mmå˜ä½ã®floatã¾ãŸã¯intã§æ›¸ã
    4. ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ã¯å¤‰æ•°ã¨ã—ã¦å†’é ­ã«ã¾ã¨ã‚ã¦å®šç¾©ã™ã‚‹
    5. ãƒ–ãƒ¼ãƒªã‚¢ãƒ³æ¼”ç®—ã¯ mode=Mode.SUBTRACTï¼ˆç©´ï¼‰ã¾ãŸã¯ mode=Mode.ADDï¼ˆåˆä½“ï¼‰ã‚’ä½¿ã†
    6. BuildSketch ã¯ãƒã‚¹ãƒˆã›ãšã€mode=Mode.SUBTRACT ã§å†…ç©´ã‚’ä½œã‚‹
    7. fillet ã¯ã™ã¹ã¦ã®å½¢çŠ¶ç¢ºå®šå¾Œã€æœ€å¾Œã«é©ç”¨ã™ã‚‹
    8. æœ€å¾Œã«å¿…ãšã“ã®2è¡Œã‚’å«ã‚ã‚‹:
       export_step(part.part, "output/llm_output.step")
       export_stl(part.part, "output/llm_output.stl")
    9. ã€æœ€é‡è¦ã€‘å¿…ãšã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯(```python\\n...\\n```)ã®ã¿è¿”ã™ã€‚
       æ—¥æœ¬èªã®èª¬æ˜ãƒ»ã‚³ãƒ¡ãƒ³ãƒˆã‚’ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®å¤–ã«æ›¸ã‹ãªã„ã€‚
       è¿”ç­”ã®æœ€åˆã®æ–‡å­—ã¯ ``` ã§ãªã‘ã‚Œã°ãªã‚‰ãªã„ã€‚

    ã€åŸºæœ¬å½¢çŠ¶ã€‘Box / Cylinder / Sphere / Cone
    ã€é…ç½®ã€‘Locations / PolarLocations / GridLocations

    ã€fillet / chamfer ã®æ­£ã—ã„æ›¸ãæ–¹ â”€ æœ€é‡è¦ã€‘
    # âœ… æ­£ã—ã„: ã‚°ãƒ­ãƒ¼ãƒãƒ«é–¢æ•°ã¨ã—ã¦å‘¼ã³å‡ºã™
    with BuildPart() as part:
        Box(100, 100, 30)
        fillet(part.edges(), radius=5)        # part.edges() ã‚’æ¸¡ã™
        chamfer(part.edges(), length=3)       # chamfer ã‚‚åŒæ§˜

    # âŒ èª¤ã‚Šï¼ˆAttributeError ã«ãªã‚‹ï¼‰
    # part.fillet(...)   â† BuildPart ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã«ã¯filletãƒ¡ã‚½ãƒƒãƒ‰ã¯ãªã„
    # part.part.fillet(...) â† ã“ã‚Œã‚‚ä¸å¯

    ã€ã‚ˆãã‚ã‚‹é–“é•ã„ã€‘
    - BuildSketchã®ãƒã‚¹ãƒˆç¦æ­¢
    - fillet/chamfer ã¯å¿…ãšå½¢çŠ¶ç¢ºå®šå¾Œã«ã‚°ãƒ­ãƒ¼ãƒãƒ«é–¢æ•°ã§å‘¼ã¶
    - part.edges() ã®ä»£ã‚ã‚Šã« part.part.edges() ã¨æ›¸ã‹ãªã„
    - filter_by_orientation / filter_by_axis ã¯å­˜åœ¨ã—ãªã„ â†’ ä½¿ã‚ãªã„
    - ç‰¹å®šã‚¨ãƒƒã‚¸ã ã‘ã«filletã—ãŸã„å ´åˆã¯ filter_by_position(Axis.Z, min, max) ã‚’ä½¿ã†
      ä¾‹: fillet(part.edges().filter_by_position(Axis.Z, 0, height), radius=3)
""")

BANNED = ['os.system','subprocess','eval(','exec(','__import__','shutil.','requests.','urllib']

# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# ã‚³ãƒ¼ãƒ‰å‡¦ç†ãƒ¦ãƒ¼ãƒ†ã‚£ãƒªãƒ†ã‚£
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
def extract_code(text):
    """LLMã®è¿”ç­”ã‹ã‚‰Pythonã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã‚’ç¢ºå®Ÿã«æŠ½å‡ºã™ã‚‹"""
    m = re.search(r'```(?:python)?[ \t]*\n(.*?)```', text, re.DOTALL)
    if m:
        return m.group(1).strip()
    m = re.search(r'(from build123d import.*)', text, re.DOTALL)
    if m:
        return m.group(1).strip()
    return ''

def validate_code_block(code, raw_response):
    if not code:
        return False, (
            'LLMãŒã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã‚’è¿”ã—ã¾ã›ã‚“ã§ã—ãŸã€‚\n'
            f'LLMã®è¿”ç­”ï¼ˆå…ˆé ­200æ–‡å­—ï¼‰:\n{raw_response[:200]}'
        )
    if 'from build123d' not in code and 'BuildPart' not in code:
        return False, (
            'Build123dã®ã‚³ãƒ¼ãƒ‰ãŒå«ã¾ã‚Œã¦ã„ã¾ã›ã‚“ã€‚\n'
            f'æŠ½å‡ºã•ã‚ŒãŸãƒ†ã‚­ã‚¹ãƒˆï¼ˆå…ˆé ­200æ–‡å­—ï¼‰:\n{code[:200]}'
        patches.append(f'  {varname}.fillet({args}) â†’ fillet({varname}.edges(), {args})')
        """
        build123d_gui.py
        â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Build123d Ã— LLM ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰
        ã‚¤ãƒ³ãƒãƒ¼ãƒˆã—ã¦ display_dashboard() ã‚’å‘¼ã¶ã ã‘ã§å®Œå…¨ãªGUIãŒè¡¨ç¤ºã•ã‚Œã¾ã™ã€‚

        ä½¿ã„æ–¹:
            import build123d_gui
            build123d_gui.display_dashboard()
        """

        from gui.dashboard import display_dashboard

        __all__ = ['display_dashboard']
        Cylinder(radius=20, height=30, mode=Mode.SUBTRACT)

export_step(hole_part.part, 'output/sample_subtract.step')
export_stl(hole_part.part,  'output/sample_subtract.stl')
print(f'âœ… Subtract ç©´ã‚ã: ä½“ç©={hole_part.part.volume:.1f} mmÂ³  â†’ output/sample_subtract.step / .stl')
""",
        },
        {
            'id': 'bolt_plate',
            'label': 'â‘£ ãƒœãƒ«ãƒˆç©´ãƒ‘ã‚¿ãƒ¼ãƒ³ï¼ˆGridLocationsï¼‰',
            'desc': (
                'Boxï¼ˆ100Ã—100Ã—15 mmï¼‰ã®å››éš…ã«ãƒœãƒ«ãƒˆç©´ï¼ˆÏ†10 mmã€70 mmãƒ”ãƒƒãƒï¼‰ã‚’é…ç½®ã€‚<br>'
                '<b>GridLocations</b> ã§å‡ç­‰ã‚°ãƒªãƒƒãƒ‰ã«ç©´ã‚’è‡ªå‹•é…ç½®ã—ã¾ã™ã€‚<br>'
                '<span class="cad-tip">PolarLocationsï¼ˆå††å‘¨å‡ç­‰é…ç½®ï¼‰ã¨çµ„ã¿åˆã‚ã›ã‚‹ã¨æ©Ÿæ¢°éƒ¨å“ã«å¿œç”¨ã§ãã¾ã™ã€‚</span>'
            ),
            'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as bolt_plate:
    Box(100, 100, 15)
    with GridLocations(70, 70, 2, 2):
        Cylinder(radius=5, height=15, mode=Mode.SUBTRACT)

export_step(bolt_plate.part, 'output/sample_bolt_plate.step')
export_stl(bolt_plate.part,  'output/sample_bolt_plate.stl')
print(f'âœ… ãƒœãƒ«ãƒˆç©´ãƒ—ãƒ¬ãƒ¼ãƒˆ: ä½“ç©={bolt_plate.part.volume:.1f} mmÂ³  â†’ output/sample_bolt_plate.step / .stl')
""",
        },
        {
            'id': 'fillet_chamfer',
            'label': 'â‘¤ ãƒ•ã‚£ãƒ¬ãƒƒãƒˆãƒ»é¢å–ã‚Šï¼ˆfillet / chamferï¼‰',
            'desc': (
                '<b>ãƒ•ã‚£ãƒ¬ãƒƒãƒˆï¼ˆR5ï¼‰</b>: Boxï¼ˆ80Ã—60Ã—25 mmï¼‰ã®ã™ã¹ã¦ã®ã‚¨ãƒƒã‚¸ã‚’ä¸¸ã‚ã‚‹ã€‚<br>'
                '<b>é¢å–ã‚Šï¼ˆC3ï¼‰</b>: åŒå½¢çŠ¶ã®ã‚¨ãƒƒã‚¸ã‚’C3ã§é¢å–ã‚Šã€‚<br>'
                '<span class="cad-tip">fillet / chamfer ã¯ã‚°ãƒ­ãƒ¼ãƒãƒ«é–¢æ•°ã¨ã—ã¦ã€å½¢çŠ¶ç¢ºå®šå¾Œã«å‘¼ã³ã¾ã™ã€‚</span>'
            ),
            'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as fillet_part:
    Box(80, 60, 25)
    fillet(fillet_part.edges(), radius=5)
export_step(fillet_part.part, 'output/sample_fillet.step')
export_stl(fillet_part.part,  'output/sample_fillet.stl')
print(f'âœ… ãƒ•ã‚£ãƒ¬ãƒƒãƒˆ R5: ä½“ç©={fillet_part.part.volume:.1f} mmÂ³  â†’ output/sample_fillet.step / .stl')

with BuildPart() as chamfer_part:
    Box(80, 60, 25)
    chamfer(chamfer_part.edges(), length=3)
export_step(chamfer_part.part, 'output/sample_chamfer.step')
export_stl(chamfer_part.part,  'output/sample_chamfer.stl')
print(f'âœ… é¢å–ã‚Š C3: ä½“ç©={chamfer_part.part.volume:.1f} mmÂ³  â†’ output/sample_chamfer.step / .stl')
""",
        },
        {
            'id': 'flange_shaft',
            'label': 'â‘¥ æ©Ÿæ¢°éƒ¨å“ï¼šãƒ•ãƒ©ãƒ³ã‚¸ä»˜ãã‚·ãƒ£ãƒ•ãƒˆ',
            'desc': (
                'ã‚·ãƒ£ãƒ•ãƒˆå¾„ Ï†30 mmã€é•·ã• 120 mm ã«<br>'
                'ãƒ•ãƒ©ãƒ³ã‚¸ï¼ˆÏ†80 mmã€åšã• 15 mmï¼‰ã‚’åˆä½“ã—ã€ãƒœãƒ«ãƒˆç©´ 4Ã—Ï†10 mmï¼ˆPCD Ï†60 mmï¼‰ä»˜ãã€‚<br>'
                'ã‚·ãƒ£ãƒ•ãƒˆæ ¹å…ƒã« R3 ãƒ•ã‚£ãƒ¬ãƒƒãƒˆã€‚<br>'
                '<span class="cad-tip">LLM ãŒç”Ÿæˆã™ã‚‹ã‚³ãƒ¼ãƒ‰ã®å…¸å‹çš„ãªä¾‹ã§ã™ã€‚ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ã‚’å¤‰ãˆã¦å¿œç”¨ã§ãã¾ã™ã€‚</span>'
            ),
            'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

shaft_diameter   = 30
shaft_length     = 120
flange_diameter  = 80
flange_thickness = 15
bolt_hole_dia    = 10
bolt_pcd         = 60
n_bolts          = 4
fillet_r         = 3

with BuildPart() as flange_shaft:
    Cylinder(radius=shaft_diameter/2, height=shaft_length)
    with Locations((0, 0, -shaft_length/2 + flange_thickness/2)):
        Cylinder(radius=flange_diameter/2, height=flange_thickness)
    with PolarLocations(bolt_pcd/2, n_bolts):
        Cylinder(radius=bolt_hole_dia/2, height=flange_thickness, mode=Mode.SUBTRACT)
    fillet(
        flange_shaft.edges().filter_by_position(
            Axis.Z,
            -shaft_length/2 + flange_thickness,
            -shaft_length/2 + flange_thickness + 1
        ),
        radius=fillet_r
    )

export_step(flange_shaft.part, 'output/sample_flange_shaft.step')
export_stl(flange_shaft.part,  'output/sample_flange_shaft.stl')
print(f'âœ… ãƒ•ãƒ©ãƒ³ã‚¸ä»˜ãã‚·ãƒ£ãƒ•ãƒˆ: ä½“ç©={flange_shaft.part.volume:.1f} mmÂ³')
print(f'   ã‚·ãƒ£ãƒ•ãƒˆå¾„: {shaft_diameter}mm, é•·ã•: {shaft_length}mm')
print(f'   ãƒ•ãƒ©ãƒ³ã‚¸å¾„: {flange_diameter}mm, ãƒœãƒ«ãƒˆç©´: {n_bolts}Ã—Ï†{bolt_hole_dia}mm')
print(f'   â†’ output/sample_flange_shaft.step / .stl')
""",
        },
        {
            'id': 'l_bracket',
            'label': 'â‘¦ æ©Ÿæ¢°éƒ¨å“ï¼šLãƒ–ãƒ©ã‚±ãƒƒãƒˆ',
            'desc': (
                'å¹…60 mmã€é«˜ã•80 mmã€å¥¥è¡Œã50 mmã€æ¿åš8 mm ã® L å­—ãƒ–ãƒ©ã‚±ãƒƒãƒˆã€‚<br>'
                'ç¸¦æ¿ã¨æ¨ªæ¿ã‚’ Union ã§åˆä½“ã—ã€æ¥åˆã‚¨ãƒƒã‚¸ã« R5 ãƒ•ã‚£ãƒ¬ãƒƒãƒˆã€‚<br>'
                '<span class="cad-tip">Locations ã§é…ç½®ã—ãŸ Box ã‚’ Union ã™ã‚‹ã“ã¨ã§ L å­—ãƒ»T å­—å½¢çŠ¶ã‚’ä½œã‚Œã¾ã™ã€‚</span>'
            ),
            'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

width     = 60
height    = 80
depth     = 50
thickness = 8

with BuildPart() as l_bracket:
    Box(thickness, width, height)
    with Locations((depth/2, 0, -height/2 + thickness/2)):
        Box(depth, width, thickness)
    fillet(l_bracket.edges().filter_by_position(Axis.X, 0, 1), radius=5)

export_step(l_bracket.part, 'output/sample_l_bracket.step')
export_stl(l_bracket.part,  'output/sample_l_bracket.stl')
print(f'âœ… Lãƒ–ãƒ©ã‚±ãƒƒãƒˆ: ä½“ç©={l_bracket.part.volume:.1f} mmÂ³')
print(f'   å¹…:{width}mm é«˜ã•:{height}mm å¥¥è¡Œã:{depth}mm æ¿åš:{thickness}mm')
print(f'   â†’ output/sample_l_bracket.step / .stl')
""",
        },
    ]

    # â”€â”€ STL ã‚¤ãƒ³ãƒ©ã‚¤ãƒ³ãƒ“ãƒ¥ãƒ¼ã‚¢ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    def _make_viewer_html(stl_path):
        """STLãƒ•ã‚¡ã‚¤ãƒ«ã‚’Base64ã‚¨ãƒ³ã‚³ãƒ¼ãƒ‰ã—ã¦Three.jsãƒ“ãƒ¥ãƒ¼ã‚¢ã®HTMLã‚’è¿”ã™"""
        import base64
        with open(stl_path, 'rb') as f:
            stl_b64 = base64.b64encode(f.read()).decode()
        fname = os.path.basename(stl_path)
        # ãƒ¦ãƒ‹ãƒ¼ã‚¯IDï¼ˆåŒä¸€ãƒãƒ¼ãƒˆãƒ–ãƒƒã‚¯å†…ã§è¤‡æ•°ãƒ“ãƒ¥ãƒ¼ã‚¢å…±å­˜ã§ãã‚‹ã‚ˆã†ï¼‰
        uid = f'v{abs(hash(stl_path)) % 99999:05d}'
        return f"""
<div id="wrap_{uid}" style="position:relative;width:100%;max-width:700px;margin:8px 0">
  <div style="font-size:12px;color:#555;margin-bottom:4px">
    ğŸ–±ï¸ ãƒ‰ãƒ©ãƒƒã‚°: å›è»¢ ï¼ ãƒ›ã‚¤ãƒ¼ãƒ«: ã‚ºãƒ¼ãƒ  ï¼ å³ãƒ‰ãƒ©ãƒƒã‚°: å¹³è¡Œç§»å‹•
    <span style="float:right;color:#888">{fname}</span>
  </div>
  <canvas id="c_{uid}" style="width:100%;height:420px;border-radius:8px;
    background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%);
    display:block"></canvas>
  <div id="err_{uid}" style="color:#f66;font-size:12px;display:none;padding:8px"></div>
</div>
<script>
(function(){{
  var STL_B64 = "{stl_b64}";
  var uid = "{uid}";

  // Base64 â†’ ArrayBuffer
  function b64ToAB(b64){{
    var bin = atob(b64), ab = new ArrayBuffer(bin.length),
        u8 = new Uint8Array(ab);
    for(var i=0;i<bin.length;i++) u8[i]=bin.charCodeAt(i);
    return ab;
  }}

  // ãƒã‚¤ãƒŠãƒªSTLè§£æ
  function parseBinarySTL(ab){{
    var dv = new DataView(ab), geo = {{}};
    var nTri = dv.getUint32(80, true);
    var pos = [], norm = [];
    var off = 84;
    for(var i=0;i<nTri;i++){{
      var nx=dv.getFloat32(off,true),
          ny=dv.getFloat32(off+4,true),
          nz=dv.getFloat32(off+8,true);
      off+=12;
      for(var v=0;v<3;v++){{
        pos.push(dv.getFloat32(off,true),
                 dv.getFloat32(off+4,true),
                 dv.getFloat32(off+8,true));
        norm.push(nx,ny,nz);
        off+=12;
      }}
      off+=2;
    }}
    geo.positions = new Float32Array(pos);
    geo.normals   = new Float32Array(norm);
    return geo;
  }}

  function loadThree(){{
    if(window.THREE && THREE.WebGLRenderer){{ initScene(); return; }}
    var s=document.createElement('script');
    s.src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js';
    s.onload=initScene;
    s.onerror=function(){{
      var e=document.getElementById('err_'+uid);
      e.textContent='Three.js ã®èª­ã¿è¾¼ã¿ã«å¤±æ•—ã—ã¾ã—ãŸï¼ˆã‚ªãƒ•ãƒ©ã‚¤ãƒ³ç’°å¢ƒã§ã¯å‹•ä½œã—ã¾ã›ã‚“ï¼‰';
      e.style.display='block';
    }};
    document.head.appendChild(s);
  }}

  function initScene(){{
    var canvas = document.getElementById('c_'+uid);
    if(!canvas) return;
    var W = canvas.clientWidth || 700, H = canvas.clientHeight || 420;
    canvas.width = W; canvas.height = H;

    var renderer = new THREE.WebGLRenderer({{canvas:canvas, antialias:true, alpha:true}});
    renderer.setPixelRatio(window.devicePixelRatio||1);
    renderer.setSize(W, H);
    renderer.shadowMap.enabled = true;

    var scene  = new THREE.Scene();
    var camera = new THREE.PerspectiveCamera(45, W/H, 0.01, 10000);

    // ãƒ©ã‚¤ãƒ†ã‚£ãƒ³ã‚°
    scene.add(new THREE.AmbientLight(0xffffff, 0.45));
    var dl = new THREE.DirectionalLight(0xffffff, 0.85);
    dl.position.set(1, 2, 3);
    scene.add(dl);
    var dl2 = new THREE.DirectionalLight(0x8888ff, 0.3);
    dl2.position.set(-2, -1, -1);
    scene.add(dl2);

    // STLèª­ã¿è¾¼ã¿
    var ab  = b64ToAB(STL_B64);
    var geo_data = parseBinarySTL(ab);
    var geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(geo_data.positions, 3));
    geo.setAttribute('normal',   new THREE.BufferAttribute(geo_data.normals,   3));

    var mat = new THREE.MeshPhongMaterial({{
      color: 0x4a90d9, specular: 0x222244,
      shininess: 60, side: THREE.DoubleSide
    }});
    var mesh = new THREE.Mesh(geo, mat);

    // ãƒ¯ã‚¤ãƒ¤ãƒ¼ãƒ•ãƒ¬ãƒ¼ãƒ 
    var wmat = new THREE.MeshBasicMaterial({{
      color: 0x88bbff, wireframe: true, opacity: 0.08, transparent: true
    }});
    mesh.add(new THREE.Mesh(geo, wmat));
    scene.add(mesh);

    // ã‚°ãƒªãƒƒãƒ‰ï¼ˆãƒ¢ãƒ‡ãƒ«ã‚µã‚¤ã‚ºã«åˆã‚ã›ãŸã‚µã‚¤ã‚ºï¼‰
    var gridSz = Math.ceil(sz * 3 / 10) * 10;
    var grid = new THREE.GridHelper(gridSz, 20, 0x334455, 0x223344);
    grid.material.opacity = 0.4; grid.material.transparent = true;
    scene.add(grid);

    // ãƒã‚¦ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ãƒœãƒƒã‚¯ã‚¹ã‹ã‚‰ãƒ¢ãƒ‡ãƒ«ã‚’åŸç‚¹ä¸­å¿ƒã«é…ç½®
    geo.computeBoundingBox();
    var bb = geo.boundingBox;
    var cx = (bb.max.x+bb.min.x)/2,
        cy = (bb.max.y+bb.min.y)/2,
        cz = (bb.max.z+bb.min.z)/2;
    var dx = bb.max.x-bb.min.x,
        dy = bb.max.y-bb.min.y,
        dz = bb.max.z-bb.min.z;
    var sz = Math.max(dx, dy, dz) || 1;
    // ãƒ¢ãƒ‡ãƒ«ã‚’åŸç‚¹ä¸­å¿ƒã¸ç§»å‹•
    mesh.position.set(-cx, -cz, cy);   // STLåº§æ¨™(X,Y,Z) â†’ Three.js(X,Z,-Y)
    grid.position.y = -(dz/2 + 2);
    // ã‚«ãƒ¡ãƒ©åˆæœŸä½ç½®
    var dist0 = sz * 2.2;

    // ãƒã‚¦ã‚¹æ“ä½œ
    var drag=false, rclick=false,
        ox=0, oy=0,
        rotX=0.4, rotY=0.6, dist=dist0,
        panX=0, panY=0;

    canvas.addEventListener('mousedown', function(e){{
      if(e.button===2) rclick=true; else drag=true;
      ox=e.clientX; oy=e.clientY; e.preventDefault();
    }});
    canvas.addEventListener('contextmenu', function(e){{e.preventDefault();}});
    window.addEventListener('mouseup', function(){{drag=false;rclick=false;}});
    window.addEventListener('mousemove', function(e){{
      var dx=e.clientX-ox, dy=e.clientY-oy; ox=e.clientX; oy=e.clientY;
      if(drag){{ rotY+=dx*0.008; rotX+=dy*0.008; }}
      if(rclick){{ panX+=dx*dist*0.001; panY-=dy*dist*0.001; }}
    }});
    canvas.addEventListener('wheel', function(e){{
      dist *= (e.deltaY>0)?1.12:0.89; e.preventDefault();
    }},{{passive:false}});

    // ã‚¿ãƒƒãƒæ“ä½œï¼ˆã‚¹ãƒãƒ›å¯¾å¿œï¼‰
    var touches={{}}, pinchDist0=0;
    canvas.addEventListener('touchstart',function(e){{
      for(var t of e.touches) touches[t.identifier]={{x:t.clientX,y:t.clientY}};
      if(e.touches.length===2){{
        var a=e.touches[0],b=e.touches[1];
        pinchDist0=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);
      }}
      e.preventDefault();
    }},{{passive:false}});
    canvas.addEventListener('touchmove',function(e){{
      if(e.touches.length===1){{
        var t=e.touches[0], prev=touches[t.identifier]||{{x:t.clientX,y:t.clientY}};
        rotY+=(t.clientX-prev.x)*0.01; rotX+=(t.clientY-prev.y)*0.01;
        touches[t.identifier]={{x:t.clientX,y:t.clientY}};
      }} else if(e.touches.length===2){{
        var a=e.touches[0],b=e.touches[1];
        var d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);
        dist*=pinchDist0/d; pinchDist0=d;
      }}
      e.preventDefault();
    }},{{passive:false}});

    function animate(){{
      requestAnimationFrame(animate);
      var x=Math.cos(rotX)*Math.sin(rotY)*dist,
          y=Math.sin(rotX)*dist,
          z=Math.cos(rotX)*Math.cos(rotY)*dist;
      camera.position.set(x+panX, y+panY, z);
      camera.lookAt(panX, panY, 0);
      renderer.render(scene, camera);
    }}
    animate();

    // ãƒªã‚µã‚¤ã‚ºå¯¾å¿œ
    var ro = new ResizeObserver(function(){{
      var W2=canvas.clientWidth, H2=canvas.clientHeight;
      renderer.setSize(W2,H2); camera.aspect=W2/H2; camera.updateProjectionMatrix();
    }});
    ro.observe(canvas);
  }}

  loadThree();
}})();
</script>"""

    def _find_latest_stl(code):
        """å®Ÿè¡Œã‚³ãƒ¼ãƒ‰ã‹ã‚‰STLãƒ‘ã‚¹ã‚’æŠ½å‡ºã—ã€ãƒãƒ¼ãƒˆãƒ–ãƒƒã‚¯ã®cwdã‚’åŸºæº–ã«çµ¶å¯¾ãƒ‘ã‚¹ã§è¿”ã™"""
        import re
        cwd = os.getcwd()
        hits = re.findall(r"export_stl\s*\([^,]+,\s*['\"]([^'\"]+\.stl)['\"]", code)
        candidates = hits if hits else []
        # ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯: output/ ä»¥ä¸‹ã§æœ€æ–°
        out_dir = os.path.join(cwd, 'output')
        if os.path.isdir(out_dir):
            stls = []
            for fn in os.listdir(out_dir):
                if fn.endswith('.stl'):
                    fp = os.path.join(out_dir, fn)
                    stls.append((os.path.getmtime(fp), fp))
            if stls:
                candidates.append(sorted(stls)[-1][1])
        # candidates ã‚’çµ¶å¯¾ãƒ‘ã‚¹ã«è§£æ±ºã—ã¦å­˜åœ¨ç¢ºèª
        for c in reversed(candidates):
            p = c if os.path.isabs(c) else os.path.join(cwd, c)
            if os.path.exists(p):
                return p
        return None

    def _show_viewer(stl_path, out_widget):
        """ç”Ÿæˆå¾Œã« out_widget ã«ãƒ“ãƒ¥ãƒ¼ã‚¢ã‚’è¡¨ç¤ºã™ã‚‹"""
        if not stl_path or not os.path.exists(stl_path):
            with out_widget:
                print(f"âš ï¸ STLãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“: {stl_path}")
            return
        try:
            html = _make_viewer_html(stl_path)
            with out_widget:
                display(HTML(html))
        except Exception as e:
            with out_widget:
                print(f"âš ï¸ ãƒ“ãƒ¥ãƒ¼ã‚¢ç”Ÿæˆã‚¨ãƒ©ãƒ¼: {e}")


    # â”€â”€ ã‚µãƒ³ãƒ—ãƒ«ã‚¿ãƒ–ã®ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆæ§‹ç¯‰ãƒ˜ãƒ«ãƒ‘ãƒ¼ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    sample_log_out    = w.Output()
    sample_code_out   = w.Output()
    sample_viewer_out = w.Output()

    def _run_sample(code, label):
        import ast as _ast, traceback as _tb
        sample_log_out.clear_output()
        sample_code_out.clear_output()
        sample_viewer_out.clear_output()
        with sample_code_out:
            display(HTML(f'<div class="cad-code">{code}</div>'))
        with sample_log_out:
            print(f'â–¶ {label} ã‚’å®Ÿè¡Œä¸­...')
        try:
            _ast.parse(code)
            exec(compile(code, '<sample>', 'exec'), {'__builtins__': __builtins__})
            with sample_log_out:
                print('âœ… ç”Ÿæˆå®Œäº†ï¼  output/ ãƒ•ã‚©ãƒ«ãƒ€ã‚’ç¢ºèªã—ã¦ãã ã•ã„ã€‚')
            stl = _find_latest_stl(code)
            if stl:
                _show_viewer(stl, sample_viewer_out)
        except Exception:
            with sample_log_out:
                print('âŒ ã‚¨ãƒ©ãƒ¼:\n' + _tb.format_exc())

    def _make_sample_row(s):
        btn = w.Button(description='â–¶ ç”Ÿæˆ', button_style='success',
                       layout=w.Layout(width='90px', height='36px'))
        desc_html = w.HTML(
            f'<div style="font-size:13px;font-weight:600;margin-bottom:3px">{s["label"]}</div>'
            f'<div style="font-size:12px;line-height:1.6">{s["desc"]}</div>'
        )
        row = w.HBox([btn, desc_html], layout=w.Layout(
            padding='10px', margin='4px 0', border='1px solid #dee2e6',
            border_radius='6px', align_items='flex-start', gap='14px'))

        def on_click(b, _code=s['code'], _label=s['label']):
            btn.disabled = True; btn.description = 'å®Ÿè¡Œä¸­...'
            _run_sample(_code, _label)
            btn.disabled = False; btn.description = 'â–¶ ç”Ÿæˆ'

        btn.on_click(on_click)
        return row

    sample_rows = [_make_sample_row(s) for s in SAMPLES]

    sample_tab = w.VBox([
        w.HTML('<div style="font-size:13px;color:#555;margin-bottom:8px">'
               'â–¶ ç”Ÿæˆ ãƒœã‚¿ãƒ³ã‚’æŠ¼ã™ã¨ã‚³ãƒ¼ãƒ‰ãŒè¡¨ç¤ºã•ã‚Œã€STEP/STL ãŒ <code>output/</code> ã«ä¿å­˜ã•ã‚Œã¾ã™ã€‚</div>'),
        *sample_rows,
        w.HTML('<hr style="margin:10px 0"><b>å®Ÿè¡Œãƒ­ã‚°</b>'),
        sample_log_out,
        w.HTML('<b>ğŸ–¥ï¸ 3Dãƒ“ãƒ¥ãƒ¼ã‚¢</b>'),
        sample_viewer_out,
        w.HTML('<b>å®Ÿè¡Œã‚³ãƒ¼ãƒ‰</b>'),
        sample_code_out,
    ], layout=w.Layout(padding='10px'))

    # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    # âš™ï¸ æ©Ÿæ¢°éƒ¨å“ã‚¿ãƒ–ï¼ˆãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿GUIä»˜ãï¼‰
    # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    mech_log_out    = w.Output()
    mech_code_out   = w.Output()
    mech_viewer_out = w.Output()

    def _run_mech(code, label):
        import ast as _ast, traceback as _tb
        mech_log_out.clear_output()
        mech_code_out.clear_output()
        mech_viewer_out.clear_output()
        with mech_code_out:
            display(HTML(f'<div class="cad-code">{code}</div>'))
        with mech_log_out:
            print(f'â–¶ {label} ã‚’å®Ÿè¡Œä¸­...')
        try:
            _ast.parse(code)
            exec(compile(code, '<mech>', 'exec'), {'__builtins__': __builtins__})
            with mech_log_out:
                print('âœ… ç”Ÿæˆå®Œäº†ï¼  output/ ãƒ•ã‚©ãƒ«ãƒ€ã‚’ç¢ºèªã—ã¦ãã ã•ã„ã€‚')
            stl = _find_latest_stl(code)
            if stl:
                _show_viewer(stl, mech_viewer_out)
        except Exception:
            with mech_log_out:
                print('âŒ ã‚¨ãƒ©ãƒ¼:\n' + _tb.format_exc())

    def _slider(desc, val, mn, mx, step, unit='mm'):
        label = w.Label(f'{desc}:', layout=w.Layout(width='160px'))
        sl = w.FloatSlider(value=val, min=mn, max=mx, step=step,
                           readout_format='.1f',
                           layout=w.Layout(width='260px'))
        unit_l = w.Label(unit, layout=w.Layout(width='36px'))
        return w.HBox([label, sl, unit_l]), sl

    def _int_slider(desc, val, mn, mx, unit=''):
        label = w.Label(f'{desc}:', layout=w.Layout(width='160px'))
        sl = w.IntSlider(value=val, min=mn, max=mx,
                         layout=w.Layout(width='260px'))
        unit_l = w.Label(unit, layout=w.Layout(width='36px'))
        return w.HBox([label, sl, unit_l]), sl

    def _section(title):
        return w.HTML(f'<div style="font-size:14px;font-weight:700;'
                      f'margin:12px 0 6px;border-bottom:2px solid #4a90d9;'
                      f'padding-bottom:4px;color:#1a3a5c">{title}</div>')

    # â”€â”€ â‘  å¹³æ­¯è»Šï¼ˆã‚¹ãƒ‘ãƒ¼ã‚®ã‚¢ï¼‰ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _sg_title = _section('âš™ï¸ â‘  å¹³æ­¯è»Šï¼ˆã‚¹ãƒ‘ãƒ¼ã‚®ã‚¢ï¼‰')
    _sg_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                     'ã‚¤ãƒ³ãƒœãƒªãƒ¥ãƒ¼ãƒˆæ­¯å½¢ã‚’ BuildSketch + spline ã§è¿‘ä¼¼ç”Ÿæˆã€‚'
                     'ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ãƒ»æ­¯æ•°ãƒ»æ­¯å¹…ã‚’èª¿æ•´ã§ãã¾ã™ã€‚</div>')
    (_sg_r1, sg_module)   = _slider('ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ« m',    2.0,  0.5, 5.0, 0.5, 'mm')
    (_sg_r2, sg_teeth)    = _int_slider('æ­¯æ•° z',       20,   8,  60, 'æš')
    (_sg_r3, sg_width)    = _slider('æ­¯å¹… b',          15.0,  5.0, 50.0, 1.0, 'mm')
    (_sg_r4, sg_press)    = _slider('åœ§åŠ›è§’ Î±',        20.0, 14.5, 25.0, 0.5, 'Â°')
    (_sg_r5, sg_hub_d)    = _slider('ãƒãƒ–å¾„',          10.0,  0.0, 30.0, 1.0, 'mm')
    (_sg_r6, sg_key_w)    = _slider('ã‚­ãƒ¼æºå¹…',         0.0,  0.0, 10.0, 0.5, 'mm')
    sg_btn = w.Button(description='â–¶ æ­¯è»Šã‚’ç”Ÿæˆ', button_style='primary',
                      layout=w.Layout(width='150px', margin='8px 0'))

    def _build_spur_gear_code():
        m   = sg_module.value
        z   = sg_teeth.value
        b   = sg_width.value
        pa  = sg_press.value
        hd  = sg_hub_d.value
        kw  = sg_key_w.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

# â”€â”€ ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ â”€â”€
m      = {m}      # ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ« [mm]
z      = {z}      # æ­¯æ•°
b      = {b}      # æ­¯å¹… [mm]
alpha  = math.radians({pa})   # åœ§åŠ›è§’
hub_d  = {hd}     # ãƒãƒ–ç©´å¾„ [mm]  0=ç©´ãªã—
key_w  = {kw}     # ã‚­ãƒ¼æºå¹… [mm]  0=ãªã—

# â”€â”€ åŸºæœ¬å¯¸æ³• â”€â”€
r   = m * z / 2
ra  = r + m
rb  = r * math.cos(alpha)
rf  = max(r - 1.25*m, rb * 0.98)
pitch = 2 * math.pi / z
t_r   = math.sqrt(max((r  / rb)**2 - 1, 0))
t_ra  = math.sqrt(max((ra / rb)**2 - 1, 0))
half  = t_r - math.atan(t_r)   # åŸºæº–å††ä¸Šã®æ­¯ã®åŠè§’

# â”€â”€ ãƒ˜ãƒ«ãƒ‘ãƒ¼ â”€â”€
def inv(rb_, t):
    return (rb_*(math.cos(t) + t*math.sin(t)),
            rb_*(math.sin(t) - t*math.cos(t)))

def rot2d(pts, a):
    ca, sa = math.cos(a), math.sin(a)
    return [(x*ca - y*sa, x*sa + y*ca) for x, y in pts]

# â”€â”€ 1æ­¯ã®ç‚¹åˆ—ï¼ˆCCWã€è§’åº¦æ¸›å°‘æ–¹å‘ï¼‰ â”€â”€
N = 10
right_flank = [inv(rb, t_ra*i/N) for i in range(N+1)]
fr = rot2d(right_flank, -half)           # å³ãƒ•ãƒ©ãƒ³ã‚¯
fl = rot2d([(-x, y) for x, y in right_flank], half)  # å·¦ãƒ•ãƒ©ãƒ³ã‚¯
fl_rev = fl[::-1]                         # ä¸‹â†’ä¸Šæ–¹å‘

a_root_left  = math.atan2(fl_rev[0][1], fl_rev[0][0])
a_root_right = math.atan2(fr[0][1],     fr[0][0])

def one_tooth():
    pts = [(rf*math.cos(a_root_left), rf*math.sin(a_root_left))]
    pts.extend(fl_rev)
    a0 = math.atan2(fl_rev[-1][1], fl_rev[-1][0])
    a1 = math.atan2(fr[-1][1],     fr[-1][0])
    if a1 > a0:
        a1 -= 2*math.pi
    for k in range(1, 3):
        a = a0 + (a1 - a0)*k/3
        pts.append((ra*math.cos(a), ra*math.sin(a)))
    pts.extend(fr[::-1])
    pts.append((rf*math.cos(a_root_right), rf*math.sin(a_root_right)))
    return pts

tooth = one_tooth()

def root_arc_pt(ae, an_raw):
    an = an_raw
    while an > ae:
        an -= 2*math.pi
    return (rf*math.cos((ae + an)/2), rf*math.sin((ae + an)/2))

# â”€â”€ å…¨æ­¯çµ„ã¿ç«‹ã¦ â”€â”€
all_pts = []
for i in range(z):
    rotated = rot2d(tooth, -pitch*i)
    all_pts.extend(rotated)
    if i < z - 1:
        ae     = math.atan2(rotated[-1][1], rotated[-1][0])
        n_next = rot2d(tooth, -pitch*(i+1))
        an_raw = math.atan2(n_next[0][1], n_next[0][0])
        all_pts.append(root_arc_pt(ae, an_raw))

# â”€â”€ ãƒ“ãƒ«ãƒ‰ â”€â”€
with BuildPart() as gear:
    with BuildSketch(Plane.XY) as sk:
        Polygon([Vector(x, y) for x, y in all_pts], align=None)
    extrude(amount=b)

    if hub_d > 0:
        with Locations((0, 0, b/2)):
            Cylinder(radius=hub_d/2, height=b+0.01, mode=Mode.SUBTRACT)

    if hub_d > 0 and key_w > 0:
        kd = key_w * 0.6
        with BuildSketch(Plane.XY.offset(b+0.01)) as sk_key:
            with Locations((hub_d/2 - kd/2, 0)):
                Rectangle(kd, key_w)
        extrude(amount=-(b+0.02), mode=Mode.SUBTRACT)

export_step(gear.part, 'output/spur_gear.step')
export_stl(gear.part,  'output/spur_gear.stl')
print(f'âœ… å¹³æ­¯è»Š m={{m}} z={{z}} b={{b}}mm')
print(f'   åŸºæº–å††å¾„: {{m*z:.2f}}mm  æ­¯å…ˆå††å¾„: {{ra*2:.2f}}mm')
print(f'   â†’ output/spur_gear.step / .stl')
"""

    def _on_sg(b):
        sg_btn.disabled = True; sg_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_spur_gear_code(), 'å¹³æ­¯è»Š')
        sg_btn.disabled = False; sg_btn.description = 'â–¶ æ­¯è»Šã‚’ç”Ÿæˆ'

    sg_btn.on_click(_on_sg)

    spur_gear_panel = w.VBox([
        _sg_title, _sg_tip,
        _sg_r1, _sg_r2, _sg_r3, _sg_r4, _sg_r5, _sg_r6,
        sg_btn,
    ])

    # â”€â”€ â‘¡ å…­è§’ãƒœãƒ«ãƒˆ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _bolt_title = _section('ğŸ”© â‘¡ å…­è§’ãƒœãƒ«ãƒˆï¼ˆJIS æº–æ‹ å½¢çŠ¶ï¼‰')
    _bolt_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                       'è»¸å¾„ãƒ»é¦–ä¸‹é•·ãƒ»ã­ã˜ãƒ”ãƒƒãƒãƒ»é ­éƒ¨ã‚µã‚¤ã‚ºã‚’èª¿æ•´ã€‚'
                       'ã­ã˜å±±ã¯èºæ—‹ã‚¹ã‚¤ãƒ¼ãƒ—ã§ç«‹ä½“çš„ã«ç”Ÿæˆã—ã¾ã™ã€‚</div>')
    (_b1, bolt_d)      = _slider('è»¸å¾„ d',         8.0,  3.0, 24.0, 1.0, 'mm')
    (_b2, bolt_len)    = _slider('é¦–ä¸‹é•· L',        40.0, 5.0,150.0, 5.0, 'mm')
    (_b3, bolt_pitch)  = _slider('ãƒ”ãƒƒãƒ p',         1.25, 0.5,  4.0, 0.25,'mm')
    (_b4, bolt_head_h) = _slider('é ­éƒ¨é«˜ã•',         5.0,  2.0, 20.0, 0.5, 'mm')
    (_b5, bolt_key_s)  = _slider('äºŒé¢å¹… (å¯¾è¾º)',    13.0,  6.0, 46.0, 1.0, 'mm')
    (_b6, bolt_thread_d)= _slider('ã­ã˜æ·±ã• (å¯¾Dæ¯”)',  0.6,  0.3,  0.9, 0.05,'Ã—d')
    bolt_btn = w.Button(description='â–¶ ãƒœãƒ«ãƒˆã‚’ç”Ÿæˆ', button_style='primary',
                        layout=w.Layout(width='150px', margin='8px 0'))

    def _build_bolt_code():
        d  = bolt_d.value
        L  = bolt_len.value
        p  = bolt_pitch.value
        hh = bolt_head_h.value
        ks = bolt_key_s.value
        td = bolt_thread_d.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

# â”€â”€ ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ â”€â”€
d        = {d}     # è»¸å¾„ [mm]
L        = {L}     # é¦–ä¸‹é•· [mm]
pitch    = {p}     # ã­ã˜ãƒ”ãƒƒãƒ [mm]
head_h   = {hh}    # é ­éƒ¨é«˜ã• [mm]
key_s    = {ks}    # äºŒé¢å¹…ï¼ˆå¯¾è¾ºï¼‰ [mm]
td_ratio = {td}    # ã­ã˜å±±æ·±ã•æ¯”ç‡

r  = d / 2
td = r * td_ratio * 0.12   # ã­ã˜å±±é«˜ã•
# â”€â”€ ã­ã˜å±±æ–­é¢ã‚’å›è»¢ä½“ã§è¿‘ä¼¼ï¼ˆè»½é‡ï¼‰â”€â”€
# XZæ–­é¢: ãƒã‚³ã‚®ãƒªæ³¢è¼ªéƒ­ã‚’ revolve
n_turns = max(2, int(L / pitch))
z_pts   = []
r_pts   = []
for i in range(n_turns):
    z0 = -L/2 + pitch * i
    z1 = z0 + pitch * 0.45
    z2 = z0 + pitch
    z_pts += [z0, z1, z2]
    r_pts += [r, r + td, r]
# è¼ªéƒ­ã‚’é–‰ã˜ã‚‹ï¼ˆè»¸å´ï¼‰
profile_pts = (
    [(r,  -L/2)]
    + list(zip(r_pts, z_pts))
    + [(r,   L/2), (r - td*0.1, L/2), (r - td*0.1, -L/2)]
)

with BuildPart() as bolt:
    # â”€â”€ è»¸éƒ¨ + ã­ã˜å±±ï¼ˆrevolveï¼‰â”€â”€
    with BuildSketch(Plane.XZ) as sk_shaft:
        Polygon([Vector(x, z) for x, z in profile_pts], align=None)
    revolve(axis=Axis.Z, revolution_arc=360)

    # â”€â”€ é ­éƒ¨ï¼ˆå…­è§’æŸ±ï¼‰â”€â”€
    with BuildSketch(Plane.XY.offset(L/2)) as sk_hex:
        RegularPolygon(radius=key_s / math.sqrt(3), side_count=6)
    extrude(amount=head_h)

    # é ­éƒ¨é¢å–ã‚Š
    chamfer(
        bolt.edges().filter_by_position(Axis.Z, L/2 + head_h - 0.01, L/2 + head_h + 0.01),
        length=min(1.0, head_h * 0.12)
    )

export_step(bolt.part, 'output/hex_bolt.step')
export_stl(bolt.part,  'output/hex_bolt.stl')
print(f'âœ… å…­è§’ãƒœãƒ«ãƒˆ M{{d:.0f}}Ã—{{L:.0f}}  p={{pitch}}mm')
print(f'   é ­éƒ¨é«˜: {{head_h}}mm  äºŒé¢å¹…: {{key_s}}mm')
print(f'   â†’ output/hex_bolt.step / .stl')
"""

    def _on_bolt(b):
        bolt_btn.disabled = True; bolt_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_bolt_code(), 'å…­è§’ãƒœãƒ«ãƒˆ')
        bolt_btn.disabled = False; bolt_btn.description = 'â–¶ ãƒœãƒ«ãƒˆã‚’ç”Ÿæˆ'

    bolt_btn.on_click(_on_bolt)

    bolt_panel = w.VBox([
        _bolt_title, _bolt_tip,
        _b1, _b2, _b3, _b4, _b5, _b6,
        bolt_btn,
    ])

    # â”€â”€ â‘¢ å…­è§’ãƒŠãƒƒãƒˆ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _nut_title = _section('ğŸ”§ â‘¢ å…­è§’ãƒŠãƒƒãƒˆï¼ˆJIS æº–æ‹ å½¢çŠ¶ï¼‰')
    _nut_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                      'å‘¼ã³å¾„ãƒ»ãƒŠãƒƒãƒˆé«˜ã•ãƒ»äºŒé¢å¹…ã‚’èª¿æ•´ã€‚'
                      'å†…éƒ¨ã­ã˜å±±ã‚‚èºæ—‹ã‚¹ã‚¤ãƒ¼ãƒ—ã§ç«‹ä½“ç”Ÿæˆã—ã¾ã™ã€‚</div>')
    (_n1, nut_d)     = _slider('å‘¼ã³å¾„ d',        8.0,  3.0, 24.0, 1.0, 'mm')
    (_n2, nut_h)     = _slider('ãƒŠãƒƒãƒˆé«˜ã• H',     6.5,  2.0, 20.0, 0.5, 'mm')
    (_n3, nut_key)   = _slider('äºŒé¢å¹… (å¯¾è¾º)',   13.0,  6.0, 46.0, 1.0, 'mm')
    (_n4, nut_pitch) = _slider('ãƒ”ãƒƒãƒ p',         1.25, 0.5,  4.0, 0.25,'mm')
    nut_btn = w.Button(description='â–¶ ãƒŠãƒƒãƒˆã‚’ç”Ÿæˆ', button_style='primary',
                       layout=w.Layout(width='150px', margin='8px 0'))

    def _build_nut_code():
        d  = nut_d.value
        H  = nut_h.value
        ks = nut_key.value
        p  = nut_pitch.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

d      = {d}    # å‘¼ã³å¾„ [mm]
H      = {H}    # ãƒŠãƒƒãƒˆé«˜ã• [mm]
key_s  = {ks}   # äºŒé¢å¹… [mm]
pitch  = {p}    # ãƒ”ãƒƒãƒ [mm]

r  = d / 2
td = r * 0.08   # ã­ã˜å±±é«˜ã•
# â”€â”€ å†…ã­ã˜å±±æ–­é¢ï¼ˆrevolve ã§è¿‘ä¼¼ï¼‰â”€â”€
n_turns = max(2, int(H / pitch))
profile_pts = [(r, -H/2)]
for i in range(n_turns):
    z0 = -H/2 + pitch * i
    z1 = z0 + pitch * 0.45
    z2 = z0 + pitch
    profile_pts += [(r - td, z0), (r, z1), (r - td, z2)]
profile_pts += [(r, H/2), (r + td*0.1, H/2), (r + td*0.1, -H/2)]

with BuildPart() as nut:
    # â”€â”€ å…­è§’æŸ±å¤–å½¢ â”€â”€
    with BuildSketch(Plane.XY) as sk_hex:
        RegularPolygon(radius=key_s / math.sqrt(3), side_count=6)
    extrude(amount=H)

    # â”€â”€ å†…ã­ã˜å±±ï¼ˆrevolve Subtractï¼‰â”€â”€
    with BuildSketch(Plane.XZ) as sk_thread:
        Polygon([Vector(x, z) for x, z in profile_pts], align=None)
    revolve(axis=Axis.Z, revolution_arc=360, mode=Mode.SUBTRACT)

    # â”€â”€ é¢å–ã‚Šï¼ˆä¸¡ç«¯ï¼‰â”€â”€
    cl = min(1.2, H * 0.1)
    chamfer(nut.edges().filter_by_position(Axis.Z, H - 0.01, H + 0.01), length=cl)
    chamfer(nut.edges().filter_by_position(Axis.Z, -0.01, 0.01), length=cl)

export_step(nut.part, 'output/hex_nut.step')
export_stl(nut.part,  'output/hex_nut.stl')
print(f'âœ… å…­è§’ãƒŠãƒƒãƒˆ M{{d:.0f}}  H={{H}}mm  äºŒé¢å¹…={{key_s}}mm')
print(f'   â†’ output/hex_nut.step / .stl')
"""

    def _on_nut(b):
        nut_btn.disabled = True; nut_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_nut_code(), 'å…­è§’ãƒŠãƒƒãƒˆ')
        nut_btn.disabled = False; nut_btn.description = 'â–¶ ãƒŠãƒƒãƒˆã‚’ç”Ÿæˆ'

    nut_btn.on_click(_on_nut)

    nut_panel = w.VBox([
        _nut_title, _nut_tip,
        _n1, _n2, _n3, _n4,
        nut_btn,
    ])

    # â”€â”€ â‘£ æ·±æºç‰è»¸å—ï¼ˆãƒ™ã‚¢ãƒªãƒ³ã‚°ï¼‰ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _brg_title = _section('ğŸ¯ â‘£ æ·±æºç‰è»¸å—ï¼ˆãƒœãƒ¼ãƒ«ãƒ™ã‚¢ãƒªãƒ³ã‚°ï¼‰')
    _brg_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                      'å†…è¼ªãƒ»å¤–è¼ªãƒ»ãƒœãƒ¼ãƒ«ãƒ»ä¿æŒå™¨ã‚’å€‹åˆ¥ã«ç”Ÿæˆã€‚'
                      'JIS å‘¼ã³ç•ªå·ã«è¿‘ã„ã‚µã‚¤ã‚ºã§èª¿æ•´ã§ãã¾ã™ã€‚</div>')
    (_br1, brg_id)     = _slider('å†…å¾„ d',         20.0, 5.0, 80.0, 1.0, 'mm')
    (_br2, brg_od)     = _slider('å¤–å¾„ D',         47.0,15.0,120.0, 1.0, 'mm')
    (_br3, brg_width)  = _slider('å¹… B',           14.0, 3.0, 30.0, 0.5, 'mm')
    (_br4, brg_balls)  = _int_slider('ãƒœãƒ¼ãƒ«æ•°',     8,   4,  20, 'å€‹')
    (_br5, brg_ball_d) = _slider('ãƒœãƒ¼ãƒ«å¾„',         6.5, 2.0, 20.0, 0.5, 'mm')
    brg_btn = w.Button(description='â–¶ ãƒ™ã‚¢ãƒªãƒ³ã‚°ã‚’ç”Ÿæˆ', button_style='primary',
                       layout=w.Layout(width='160px', margin='8px 0'))

    def _build_bearing_code():
        di = brg_id.value
        do = brg_od.value
        bw = brg_width.value
        nb = brg_balls.value
        bd = brg_ball_d.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

inner_d   = {di}    # å†…å¾„ [mm]
outer_d   = {do}    # å¤–å¾„ [mm]
width     = {bw}    # å¹… [mm]
n_balls   = {nb}    # ãƒœãƒ¼ãƒ«æ•°
ball_d    = {bd}    # ãƒœãƒ¼ãƒ«å¾„ [mm]

ri = inner_d / 2
ro = outer_d / 2
race_r   = (ri + ro) / 2    # ãƒœãƒ¼ãƒ«è»Œé“åŠå¾„
groove_r = ball_d / 2 * 1.06

# â”€â”€ å¤–è¼ªï¼ˆXZæ–­é¢ â†’ revolveï¼‰â”€â”€
ow = (ro - race_r) * 0.88          # å¤–è¼ªã®åŠå¹…
with BuildPart() as outer_ring:
    with BuildSketch(Plane.XZ) as sk_or:
        # å¤–è¼ªæ–­é¢ï¼ˆçŸ©å½¢ - æºï¼‰
        with Locations((race_r + ow/2 + ball_d*0.02, 0)):
            Rectangle(ow, width)
        with Locations((race_r, 0)):
            Circle(groove_r, mode=Mode.SUBTRACT)
    revolve(axis=Axis.Z, revolution_arc=360)

# â”€â”€ å†…è¼ªï¼ˆXZæ–­é¢ â†’ revolveï¼‰â”€â”€
iw = (race_r - ri) * 0.88
with BuildPart() as inner_ring:
    with BuildSketch(Plane.XZ) as sk_ir:
        with Locations((ri + iw/2 + ball_d*0.02, 0)):
            Rectangle(iw, width)
        with Locations((race_r, 0)):
            Circle(groove_r, mode=Mode.SUBTRACT)
    revolve(axis=Axis.Z, revolution_arc=360)

# â”€â”€ ãƒœãƒ¼ãƒ«ç¾¤ â”€â”€
with BuildPart() as balls:
    with PolarLocations(race_r, n_balls):
        Sphere(radius=ball_d / 2)

# â”€â”€ ä¿æŒå™¨ï¼ˆä¸Šä¸‹ãƒªãƒ  + ãƒã‚¹ãƒˆï¼‰â”€â”€
cage_t  = ball_d * 0.22
rim_h   = width * 0.22
with BuildPart() as cage:
    # ä¸Šãƒªãƒ 
    with BuildSketch(Plane.XY.offset(width * 0.28)) as sk_top:
        Circle(race_r + cage_t)
        Circle(race_r - cage_t, mode=Mode.SUBTRACT)
    extrude(amount=rim_h)
    # ä¸‹ãƒªãƒ 
    with BuildSketch(Plane.XY.offset(-width * 0.28 - rim_h)) as sk_bot:
        Circle(race_r + cage_t)
        Circle(race_r - cage_t, mode=Mode.SUBTRACT)
    extrude(amount=rim_h)
    # ãƒã‚±ãƒƒãƒˆç©´
    with PolarLocations(race_r, n_balls):
        Cylinder(radius=ball_d * 0.54, height=width, mode=Mode.SUBTRACT)

for part, name in [
    (outer_ring, 'bearing_outer'),
    (inner_ring, 'bearing_inner'),
    (balls,      'bearing_balls'),
    (cage,       'bearing_cage'),
]:
    export_step(part.part, f'output/{{name}}.step')
    export_stl(part.part,  f'output/{{name}}.stl')

print(f'âœ… æ·±æºç‰è»¸å—  å†…å¾„{{inner_d}}Ã—å¤–å¾„{{outer_d}}Ã—å¹…{{width}}mm')
print(f'   ãƒœãƒ¼ãƒ« {{n_balls}}å€‹ Ï†{{ball_d}}mm')
print(f'   â†’ output/bearing_*.step / .stlï¼ˆå¤–è¼ªãƒ»å†…è¼ªãƒ»ãƒœãƒ¼ãƒ«ãƒ»ä¿æŒå™¨ï¼‰')
"""

    def _on_brg(b):
        brg_btn.disabled = True; brg_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_bearing_code(), 'æ·±æºç‰è»¸å—')
        brg_btn.disabled = False; brg_btn.description = 'â–¶ ãƒ™ã‚¢ãƒªãƒ³ã‚°ã‚’ç”Ÿæˆ'

    brg_btn.on_click(_on_brg)

    bearing_panel = w.VBox([
        _brg_title, _brg_tip,
        _br1, _br2, _br3, _br4, _br5,
        brg_btn,
    ])

    # â”€â”€ â‘¤ ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ï¼ˆã‚¨ãƒ«ãƒœï¼‰ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _elbow_title = _section('ğŸ”„ â‘¤ ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ï¼ˆã‚¨ãƒ«ãƒœ / ã‚¹ã‚¤ãƒ¼ãƒ—ï¼‰')
    _elbow_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                        'å††å¼§ãƒ‘ã‚¹ä¸Šã«ç’°çŠ¶æ–­é¢ã‚’ã‚¹ã‚¤ãƒ¼ãƒ—ã€‚'
                        'æ›²ãŒã‚Šè§’åº¦ãƒ»ãƒ‘ã‚¤ãƒ—å¾„ãƒ»è‚‰åšã‚’è‡ªç”±ã«è¨­å®šã§ãã¾ã™ã€‚</div>')
    (_el1, elbow_od)    = _slider('å¤–å¾„ D',         42.0, 10.0,120.0, 2.0, 'mm')
    (_el2, elbow_t)     = _slider('è‚‰åš t',          3.5,  1.0, 15.0, 0.5, 'mm')
    (_el3, elbow_r)     = _slider('æ›²ç‡åŠå¾„ R',      60.0, 20.0,200.0, 5.0, 'mm')
    (_el4, elbow_angle) = _slider('æ›²ãŒã‚Šè§’åº¦ Î¸',    90.0, 15.0,180.0, 5.0, 'Â°')
    (_el5, elbow_ext)   = _slider('ç›´ç®¡å»¶é•·',         20.0,  0.0, 80.0, 5.0, 'mm')
    elbow_btn = w.Button(description='â–¶ ç¶™æ‰‹ã‚’ç”Ÿæˆ', button_style='primary',
                         layout=w.Layout(width='150px', margin='8px 0'))

    def _build_elbow_code():
        od    = elbow_od.value
        t     = elbow_t.value
        R     = elbow_r.value
        angle = elbow_angle.value
        ext   = elbow_ext.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

outer_d = {od}    # å¤–å¾„ [mm]
wall_t  = {t}     # è‚‰åš [mm]
bend_R  = {R}     # æ›²ç‡åŠå¾„ [mm]
angle   = {angle} # æ›²ãŒã‚Šè§’åº¦ [Â°]
ext_len = {ext}   # ç›´ç®¡å»¶é•· [mm]

ro = outer_d / 2
ri = ro - wall_t

with BuildPart() as elbow:
    # â”€â”€ æ›²ãŒã‚Šéƒ¨ï¼ˆCenterArc ã‚¹ã‚¤ãƒ¼ãƒ—ï¼‰â”€â”€
    path = CenterArc(
        center=(bend_R, 0),
        radius=bend_R,
        start_angle=180,
        arc_size=-angle
    )
    with BuildSketch(
        Plane(origin=path.start_location.position,
              z_dir=path.start_location.z_axis)
    ) as sk_pipe:
        Circle(ro)
        Circle(ri, mode=Mode.SUBTRACT)
    sweep(path=path)

    # â”€â”€ ç›´ç®¡ï¼ˆå…¥å£å´ï¼‰â”€â”€
    if ext_len > 0:
        start_pos = path.start_location.position
        start_dir = path.start_location.z_axis
        with BuildSketch(Plane(origin=start_pos, z_dir=start_dir)) as sk_ext1:
            Circle(ro)
            Circle(ri, mode=Mode.SUBTRACT)
        extrude(amount=ext_len)

    # â”€â”€ ç›´ç®¡ï¼ˆå‡ºå£å´ï¼‰â”€â”€
    if ext_len > 0:
        end_pos = path.end_location.position
        end_dir = path.end_location.z_axis
        with BuildSketch(Plane(origin=end_pos, z_dir=end_dir)) as sk_ext2:
            Circle(ro)
            Circle(ri, mode=Mode.SUBTRACT)
        extrude(amount=ext_len)

export_step(elbow.part, 'output/pipe_elbow.step')
export_stl(elbow.part,  'output/pipe_elbow.stl')
print(f'âœ… ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ Ï†{{outer_d}}Ã—t{{wall_t}} R={{bend_R}}mm {{angle}}Â°')
print(f'   â†’ output/pipe_elbow.step / .stl')
"""

    def _on_elbow(b):
        elbow_btn.disabled = True; elbow_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_elbow_code(), 'ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹')
        elbow_btn.disabled = False; elbow_btn.description = 'â–¶ ç¶™æ‰‹ã‚’ç”Ÿæˆ'

    elbow_btn.on_click(_on_elbow)

    elbow_panel = w.VBox([
        _elbow_title, _elbow_tip,
        _el1, _el2, _el3, _el4, _el5,
        elbow_btn,
    ])

    # â”€â”€ â‘¥ Vãƒ—ãƒ¼ãƒªãƒ¼ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    _pulley_title = _section('ğŸ”˜ â‘¥ Vãƒ—ãƒ¼ãƒªãƒ¼ï¼ˆãƒ­ãƒ•ãƒˆæºï¼‰')
    _pulley_tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                         'Vãƒ™ãƒ«ãƒˆç”¨ã®æºå½¢çŠ¶ã‚’ BuildSketch + revolve ã§ç”Ÿæˆã€‚'
                         'æºæ•°ãƒ»ãƒ—ãƒ¼ãƒªãƒ¼å¾„ãƒ»Vè§’åº¦ã‚’å¤‰æ›´ã§ãã¾ã™ã€‚</div>')
    (_pl1, pulley_od)    = _slider('å¤–å¾„ D',       100.0, 30.0,300.0, 5.0, 'mm')
    (_pl2, pulley_hub)   = _slider('ãƒãƒ–å¾„',         25.0,  8.0, 60.0, 1.0, 'mm')
    (_pl3, pulley_width) = _slider('ãƒ—ãƒ¼ãƒªãƒ¼å¹…',     40.0, 10.0,120.0, 2.0, 'mm')
    (_pl4, pulley_grooves)= _int_slider('æºæ•°',      2,    1,   6, 'æœ¬')
    (_pl5, pulley_v_angle)= _slider('Vè§’åº¦ (ç‰‡å´)', 17.0,  8.0, 25.0, 1.0, 'Â°')
    (_pl6, pulley_groove_d)= _slider('æºæ·±ã•',        8.0,  3.0, 20.0, 0.5, 'mm')
    pulley_btn = w.Button(description='â–¶ ãƒ—ãƒ¼ãƒªãƒ¼ã‚’ç”Ÿæˆ', button_style='primary',
                          layout=w.Layout(width='160px', margin='8px 0'))

    def _build_pulley_code():
        od  = pulley_od.value
        hd  = pulley_hub.value
        pw  = pulley_width.value
        ng  = pulley_grooves.value
        va  = pulley_v_angle.value
        gd  = pulley_groove_d.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

outer_d    = {od}   # å¤–å¾„ [mm]
hub_d      = {hd}   # ãƒãƒ–å¾„ [mm]
pwidth     = {pw}   # ãƒ—ãƒ¼ãƒªãƒ¼å¹… [mm]
n_grooves  = {ng}   # æºæ•°
v_half     = math.radians({va})  # Vè§’ï¼ˆç‰‡å´ï¼‰
groove_d   = {gd}   # æºæ·±ã• [mm]
web_t      = pwidth * 0.15        # ã‚¦ã‚§ãƒ–åšã•

ro = outer_d / 2
rh = hub_d / 2
groove_spacing = pwidth / (n_grooves + 1)

with BuildPart() as pulley:
    # â”€â”€ å¤–è¼ªãƒªãƒ ï¼ˆå›è»¢ä½“ï¼‰â”€â”€
    with BuildSketch(Plane.XZ) as sk_rim:
        with Locations((ro - 2, 0)):
            Rectangle(4, pwidth)
    revolve(axis=Axis.Z, revolution_arc=360)

    # â”€â”€ ã‚¦ã‚§ãƒ– â”€â”€
    with BuildSketch(Plane.XZ) as sk_web:
        with Locations(((ro + rh) / 2, 0)):
            Rectangle(ro - rh, web_t)
    revolve(axis=Axis.Z, revolution_arc=360)

    # â”€â”€ ãƒãƒ– â”€â”€
    Cylinder(radius=rh + 5, height=pwidth)
    with Locations((0, 0, 0)):
        Cylinder(radius=rh, height=pwidth, mode=Mode.SUBTRACT)

    # â”€â”€ Væºï¼ˆè¤‡æ•°ï¼‰â”€â”€
    for i in range(n_grooves):
        z_pos = -pwidth/2 + groove_spacing * (i + 1)
        groove_top_w = groove_d * math.tan(v_half) * 2
        with BuildSketch(Plane.XZ) as sk_groove:
            # Vå½¢æ–­é¢ï¼ˆä¸‰è§’å½¢ï¼‰
            pts = [
                Vector(ro,            z_pos - groove_top_w / 2),
                Vector(ro - groove_d, z_pos),
                Vector(ro,            z_pos + groove_top_w / 2),
                Vector(ro + 1,        z_pos + groove_top_w / 2),
                Vector(ro + 1,        z_pos - groove_top_w / 2),
            ]
            Polygon(pts, align=None)
        revolve(axis=Axis.Z, revolution_arc=360, mode=Mode.SUBTRACT)

export_step(pulley.part, 'output/v_pulley.step')
export_stl(pulley.part,  'output/v_pulley.stl')
print(f'âœ… Vãƒ—ãƒ¼ãƒªãƒ¼ Ï†{{outer_d}} å¹…{{pwidth}}mm {{n_grooves}}æº')
print(f'   â†’ output/v_pulley.step / .stl')
"""

    def _on_pulley(b):
        pulley_btn.disabled = True; pulley_btn.description = 'å®Ÿè¡Œä¸­...'
        _run_mech(_build_pulley_code(), 'Vãƒ—ãƒ¼ãƒªãƒ¼')
        pulley_btn.disabled = False; pulley_btn.description = 'â–¶ ãƒ—ãƒ¼ãƒªãƒ¼ã‚’ç”Ÿæˆ'

    pulley_btn.on_click(_on_pulley)

    pulley_panel = w.VBox([
        _pulley_title, _pulley_tip,
        _pl1, _pl2, _pl3, _pl4, _pl5, _pl6,
        pulley_btn,
    ])

    # â”€â”€ æ©Ÿæ¢°éƒ¨å“ã‚¿ãƒ–çµ„ç«‹ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    mech_accordion = w.Accordion(children=[
        spur_gear_panel, bolt_panel, nut_panel,
        bearing_panel, elbow_panel, pulley_panel,
    ])
    for i, title in enumerate([
        'âš™ï¸ â‘  å¹³æ­¯è»Šï¼ˆã‚¹ãƒ‘ãƒ¼ã‚®ã‚¢ï¼‰',
        'ğŸ”© â‘¡ å…­è§’ãƒœãƒ«ãƒˆ',
        'ğŸ”§ â‘¢ å…­è§’ãƒŠãƒƒãƒˆ',
        'ğŸ¯ â‘£ æ·±æºç‰è»¸å—ï¼ˆãƒ™ã‚¢ãƒªãƒ³ã‚°ï¼‰',
        'ğŸ”„ â‘¤ ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ï¼ˆã‚¨ãƒ«ãƒœï¼‰',
        'ğŸ”˜ â‘¥ Vãƒ—ãƒ¼ãƒªãƒ¼',
    ]):
        mech_accordion.set_title(i, title)
    mech_accordion.selected_index = 0

    mech_tab = w.VBox([
        w.HTML('<div style="font-size:13px;color:#555;margin-bottom:8px">'
               'ã‚¢ã‚³ãƒ¼ãƒ‡ã‚£ã‚ªãƒ³ã§éƒ¨å“ã‚’é¸ã³ã€ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ã‚’èª¿æ•´ã—ã¦ â–¶ ç”Ÿæˆ ãƒœã‚¿ãƒ³ã‚’æŠ¼ã—ã¦ãã ã•ã„ã€‚<br>'
               'STEP / STL ãŒ <code>output/</code> ã«ä¿å­˜ã•ã‚Œã¾ã™ã€‚</div>'),
        mech_accordion,
        w.HTML('<hr style="margin:10px 0"><b>å®Ÿè¡Œãƒ­ã‚°</b>'),
        mech_log_out,
        w.HTML('<b>ğŸ–¥ï¸ 3Dãƒ“ãƒ¥ãƒ¼ã‚¢</b>'),
        mech_viewer_out,
        w.HTML('<b>å®Ÿè¡Œã‚³ãƒ¼ãƒ‰</b>'),
        mech_code_out,
    ], layout=w.Layout(padding='10px'))

    # â”€â”€ ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰çµ„ç«‹ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    tabs = w.Tab(children=[settings_tab, api_tab, manual_tab, sample_tab, mech_tab, hist_tab])
    tabs.set_title(0, 'âš™ï¸ APIè¨­å®š')
    tabs.set_title(1, 'ğŸ¤– API è‡ªå‹•ç”Ÿæˆ')
    tabs.set_title(2, 'ğŸ“‹ Manual')
    tabs.set_title(3, 'ğŸ”¬ ã‚µãƒ³ãƒ—ãƒ«')
    tabs.set_title(4, 'ğŸ”© æ©Ÿæ¢°éƒ¨å“')
    tabs.set_title(5, 'ğŸ“œ ä¼šè©±å±¥æ­´')

    dashboard = w.VBox([
        w.HTML('<h3 style="margin:4px 0 8px">ğŸ”§ Build123d Ã— LLM ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰</h3>'),
        tabs,
    ], layout=w.Layout(padding='8px'))

    display(dashboard)
    print('âœ… GUI èµ·å‹•å®Œäº†  â”€  ã¾ãšã€Œâš™ï¸ APIè¨­å®šã€ã‚¿ãƒ–ã§ãƒ¢ãƒ¼ãƒ‰ã¨ã‚­ãƒ¼ã‚’è¨­å®šã—ã¦ãã ã•ã„')
