"""
gui/tabs/machine_parts/bearing_panel.py
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
æ·±æºç‰è»¸å—ï¼ˆãƒ™ã‚¢ãƒªãƒ³ã‚°ï¼‰ãƒ‘ãƒãƒ«ã€‚
"""
import ipywidgets as w
from .base_panel import MachinePartPanel


class BearingPanel(MachinePartPanel):
    title = 'ğŸ¯ â‘£ æ·±æºç‰è»¸å—ï¼ˆãƒ™ã‚¢ãƒªãƒ³ã‚°ï¼‰'

    def __init__(self) -> None:
        self.log_out    = w.Output()
        self.viewer_out = w.Output()
        self.code_out   = w.Output()
        self._tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                           'å†…è¼ªãƒ»å¤–è¼ªãƒ»ãƒœãƒ¼ãƒ«ãƒ»ä¿æŒå™¨ã‚’å€‹åˆ¥ã«ç”Ÿæˆã€‚'
                           'JIS å‘¼ã³ç•ªå·ã«è¿‘ã„ã‚µã‚¤ã‚ºã§èª¿æ•´ã§ãã¾ã™ã€‚</div>')
        (_br1, self.brg_id)    = self._slider('å†…å¾„ d',         20.0,  5.0, 80.0, 1.0, 'mm')
        (_br2, self.brg_od)    = self._slider('å¤–å¾„ D',         47.0, 15.0,120.0, 1.0, 'mm')
        (_br3, self.brg_width) = self._slider('å¹… B',           14.0,  3.0, 30.0, 0.5, 'mm')
        (_br4, self.brg_balls) = self._int_slider('ãƒœãƒ¼ãƒ«æ•°',     8,    4,   20, 'å€‹')
        (_br5, self.brg_ball_d)= self._slider('ãƒœãƒ¼ãƒ«å¾„',         6.5,  2.0, 20.0, 0.5, 'mm')
        self._rows = [_br1, _br2, _br3, _br4, _br5]
        self._btn = w.Button(description='â–¶ ãƒ™ã‚¢ãƒªãƒ³ã‚°ã‚’ç”Ÿæˆ', button_style='primary',
                             layout=w.Layout(width='160px', margin='8px 0'))
        self._btn.on_click(self._on_click)

    def _on_click(self, b: w.Button) -> None:
        self._btn.disabled = True
        self._btn.description = 'å®Ÿè¡Œä¸­...'
        self._run('æ·±æºç‰è»¸å—')
        self._btn.disabled = False
        self._btn.description = 'â–¶ ãƒ™ã‚¢ãƒªãƒ³ã‚°ã‚’ç”Ÿæˆ'

    def _build_code(self) -> str:
        di = self.brg_id.value
        do = self.brg_od.value
        bw = self.brg_width.value
        nb = self.brg_balls.value
        bd = self.brg_ball_d.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

inner_d   = {di}    # å†…å¾„ [mm]
outer_d   = {do}    # å¤–å¾„ [mm]
width     = {bw}    # å¹… [mm]
n_balls   = {nb}    # ãƒœãƒ¼ãƒ«æ•°
ball_d    = {bd}    # ãƒœãƒ¼ãƒ«å¾„ [mm]

ri = inner_d / 2
ro = outer_d / 2
race_r   = (ri + ro) / 2    # ãƒœãƒ¼ãƒ«è»Œé“åŠå¾„
groove_r = ball_d / 2 * 1.06

# â”€â”€ å¤–è¼ªï¼ˆXZæ–­é¢ â†’ revolveï¼‰â”€â”€
ow = (ro - race_r) * 0.88          # å¤–è¼ªã®åŠå¹…
with BuildPart() as outer_ring:
    with BuildSketch(Plane.XZ) as sk_or:
        # å¤–è¼ªæ–­é¢ï¼ˆçŸ©å½¢ - æºï¼‰
        with Locations((race_r + ow/2 + ball_d*0.02, 0)):
            Rectangle(ow, width)
        with Locations((race_r, 0)):
            Circle(groove_r, mode=Mode.SUBTRACT)
    revolve(axis=Axis.Z, revolution_arc=360)

# â”€â”€ å†…è¼ªï¼ˆXZæ–­é¢ â†’ revolveï¼‰â”€â”€
iw = (race_r - ri) * 0.88
with BuildPart() as inner_ring:
    with BuildSketch(Plane.XZ) as sk_ir:
        with Locations((ri + iw/2 + ball_d*0.02, 0)):
            Rectangle(iw, width)
        with Locations((race_r, 0)):
            Circle(groove_r, mode=Mode.SUBTRACT)
    revolve(axis=Axis.Z, revolution_arc=360)

# â”€â”€ ãƒœãƒ¼ãƒ«ç¾¤ â”€â”€
with BuildPart() as balls:
    with PolarLocations(race_r, n_balls):
        Sphere(radius=ball_d / 2)

# â”€â”€ ä¿æŒå™¨ï¼ˆä¸Šä¸‹ãƒªãƒ  + ãƒã‚¹ãƒˆï¼‰â”€â”€
cage_t  = ball_d * 0.22
rim_h   = width * 0.22
with BuildPart() as cage:
    # ä¸Šãƒªãƒ 
    with BuildSketch(Plane.XY.offset(width * 0.28)) as sk_top:
        Circle(race_r + cage_t)
        Circle(race_r - cage_t, mode=Mode.SUBTRACT)
    extrude(amount=rim_h)
    # ä¸‹ãƒªãƒ 
    with BuildSketch(Plane.XY.offset(-width * 0.28 - rim_h)) as sk_bot:
        Circle(race_r + cage_t)
        Circle(race_r - cage_t, mode=Mode.SUBTRACT)
    extrude(amount=rim_h)
    # ãƒã‚±ãƒƒãƒˆç©´
    with PolarLocations(race_r, n_balls):
        Cylinder(radius=ball_d * 0.54, height=width, mode=Mode.SUBTRACT)

for part, name in [
    (outer_ring, 'bearing_outer'),
    (inner_ring, 'bearing_inner'),
    (balls,      'bearing_balls'),
    (cage,       'bearing_cage'),
]:
    export_step(part.part, f'output/{{name}}.step')
    export_stl(part.part,  f'output/{{name}}.stl')
show_object = [v for k, v in locals().items() if k in ("outer_ring", "inner_ring", "balls", "cage", "cage_parts")]

print(f'âœ… æ·±æºç‰è»¸å—  å†…å¾„{{inner_d}}Ã—å¤–å¾„{{outer_d}}Ã—å¹…{{width}}mm')
print(f'   ãƒœãƒ¼ãƒ« {{n_balls}}å€‹ Ï†{{ball_d}}mm')
print(f'   â†’ output/bearing_*.step / .stlï¼ˆå¤–è¼ªãƒ»å†…è¼ªãƒ»ãƒœãƒ¼ãƒ«ãƒ»ä¿æŒå™¨ï¼‰')
"""

    def build_widget(self) -> w.VBox:
        return w.VBox([
            self._section(self.title),
            self._tip,
            *self._rows,
            self._btn,
        ])
