"""
gui/tabs/machine_parts/hex_bolt_panel.py
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
å…­è§’ãƒœãƒ«ãƒˆãƒ‘ãƒãƒ«ã€‚
"""
import ipywidgets as w
from .base_panel import MachinePartPanel


class HexBoltPanel(MachinePartPanel):
    title = 'ğŸ”© â‘¡ å…­è§’ãƒœãƒ«ãƒˆ'

    def __init__(self) -> None:
        self.log_out    = w.Output()
        self.viewer_out = w.Output()
        self.code_out   = w.Output()
        self._tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                           'è»¸å¾„ãƒ»é¦–ä¸‹é•·ãƒ»ã­ã˜ãƒ”ãƒƒãƒãƒ»é ­éƒ¨ã‚µã‚¤ã‚ºã‚’èª¿æ•´ã€‚'
                           'ã­ã˜å±±ã¯èºæ—‹ã‚¹ã‚¤ãƒ¼ãƒ—ã§ç«‹ä½“çš„ã«ç”Ÿæˆã—ã¾ã™ã€‚</div>')
        (_b1, self.bolt_d)       = self._slider('è»¸å¾„ d',          8.0,  3.0, 24.0, 1.0,  'mm')
        (_b2, self.bolt_len)     = self._slider('é¦–ä¸‹é•· L',        40.0,  5.0,150.0, 5.0,  'mm')
        (_b3, self.bolt_pitch)   = self._slider('ãƒ”ãƒƒãƒ p',         1.25, 0.5,  4.0, 0.25, 'mm')
        (_b4, self.bolt_head_h)  = self._slider('é ­éƒ¨é«˜ã•',          5.0,  2.0, 20.0, 0.5,  'mm')
        (_b5, self.bolt_key_s)   = self._slider('äºŒé¢å¹… (å¯¾è¾º)',    13.0,  6.0, 46.0, 1.0,  'mm')
        (_b6, self.bolt_thread_d)= self._slider('ã­ã˜æ·±ã• (å¯¾Dæ¯”)',  0.6,  0.3,  0.9, 0.05, 'Ã—d')
        self._rows = [_b1, _b2, _b3, _b4, _b5, _b6]
        self._btn = w.Button(description='â–¶ ãƒœãƒ«ãƒˆã‚’ç”Ÿæˆ', button_style='primary',
                             layout=w.Layout(width='150px', margin='8px 0'))
        self._btn.on_click(self._on_click)

    def _on_click(self, b: w.Button) -> None:
        self._btn.disabled = True
        self._btn.description = 'å®Ÿè¡Œä¸­...'
        self._run('å…­è§’ãƒœãƒ«ãƒˆ')
        self._btn.disabled = False
        self._btn.description = 'â–¶ ãƒœãƒ«ãƒˆã‚’ç”Ÿæˆ'

    def _build_code(self) -> str:
        d  = self.bolt_d.value
        L  = self.bolt_len.value
        p  = self.bolt_pitch.value
        hh = self.bolt_head_h.value
        ks = self.bolt_key_s.value
        td = self.bolt_thread_d.value
        return f"""\
from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

# â”€â”€ ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ â”€â”€
d        = {d}     # è»¸å¾„ [mm]
L        = {L}     # é¦–ä¸‹é•· [mm]
pitch    = {p}     # ã­ã˜ãƒ”ãƒƒãƒ [mm]
head_h   = {hh}    # é ­éƒ¨é«˜ã• [mm]
key_s    = {ks}    # äºŒé¢å¹…ï¼ˆå¯¾è¾ºï¼‰ [mm]
td_ratio = {td}    # ã­ã˜å±±æ·±ã•æ¯”ç‡

r  = d / 2
td = r * td_ratio * 0.12   # ã­ã˜å±±é«˜ã•
# â”€â”€ ã­ã˜å±±æ–­é¢ã‚’å›è»¢ä½“ã§è¿‘ä¼¼ï¼ˆè»½é‡ï¼‰â”€â”€
# XZæ–­é¢: ãƒã‚³ã‚®ãƒªæ³¢è¼ªéƒ­ã‚’ revolve
n_turns = max(2, int(L / pitch))
z_pts   = []
r_pts   = []
for i in range(n_turns):
    z0 = -L/2 + pitch * i
    z1 = z0 + pitch * 0.45
    z2 = z0 + pitch
    z_pts += [z0, z1, z2]
    r_pts += [r, r + td, r]
# è¼ªéƒ­ã‚’é–‰ã˜ã‚‹ï¼ˆè»¸å´ï¼‰
profile_pts = (
    [(r,  -L/2)]
    + list(zip(r_pts, z_pts))
    + [(r,   L/2), (r - td*0.1, L/2), (r - td*0.1, -L/2)]
)

with BuildPart() as bolt:
    # â”€â”€ è»¸éƒ¨ + ã­ã˜å±±ï¼ˆrevolveï¼‰â”€â”€
    with BuildSketch(Plane.XZ) as sk_shaft:
        make_face(Polyline([Vector(x, z) for x, z in profile_pts], close=True))
    revolve(axis=Axis.Z, revolution_arc=360)

    # â”€â”€ é ­éƒ¨ï¼ˆå…­è§’æŸ±ï¼‰â”€â”€
    with BuildSketch(Plane.XY.offset(L/2)) as sk_hex:
        RegularPolygon(radius=key_s / math.sqrt(3), side_count=6)
    extrude(amount=head_h)

    # é ­éƒ¨é¢å–ã‚Š
    chamfer(
        bolt.edges().filter_by_position(Axis.Z, L/2 + head_h - 0.01, L/2 + head_h + 0.01),
        length=min(1.0, head_h * 0.12)
    )

export_step(bolt.part, 'output/hex_bolt.step')
export_stl(bolt.part,  'output/hex_bolt.stl')
show_object = bolt
print(f'âœ… å…­è§’ãƒœãƒ«ãƒˆ M{{d:.0f}}Ã—{{L:.0f}}  p={{pitch}}mm')
print(f'   é ­éƒ¨é«˜: {{head_h}}mm  äºŒé¢å¹…: {{key_s}}mm')
print(f'   â†’ output/hex_bolt.step / .stl')
"""

    def build_widget(self) -> w.VBox:
        return w.VBox([
            self._section(self.title),
            self._tip,
            *self._rows,
            self._btn,
        ])
