"""
gui/tabs/machine_parts/pipe_fitting_panel.py
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ï¼ˆã‚¨ãƒ«ãƒœï¼‰ãƒ‘ãƒãƒ«ã€‚
ã€ä¿®æ­£ã€‘CenterArc ã¯ BuildLine å†…ã§ä½¿ç”¨ã—ã€sweep ã®ãƒ‘ã‚¹ã¨ã—ã¦æ¸¡ã™æ­£ã—ã„æ–¹æ³•ã«å¤‰æ›´ã€‚
ç›´ç®¡å»¶é•·ã¯ elbow ç«¯é¢ã‹ã‚‰æŠ¼ã—å‡ºã™æ–¹å¼ã«å¤‰æ›´ã€‚
"""
import ipywidgets as w
from .base_panel import MachinePartPanel


class PipeFittingPanel(MachinePartPanel):
    title = 'ğŸ”„ â‘¤ ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ï¼ˆã‚¨ãƒ«ãƒœï¼‰'

    def __init__(self) -> None:
        self.log_out    = w.Output()
        self.viewer_out = w.Output()
        self.code_out   = w.Output()
        self._tip = w.HTML('<div class="cad-tip" style="margin-bottom:6px">'
                           'å††å¼§ãƒ‘ã‚¹ä¸Šã«ç’°çŠ¶æ–­é¢ã‚’ã‚¹ã‚¤ãƒ¼ãƒ—ã€‚'
                           'æ›²ãŒã‚Šè§’åº¦ãƒ»ãƒ‘ã‚¤ãƒ—å¾„ãƒ»è‚‰åšã‚’è‡ªç”±ã«è¨­å®šã§ãã¾ã™ã€‚</div>')
        (_el1, self.elbow_od)    = self._slider('å¤–å¾„ D',       42.0, 10.0, 120.0, 2.0, 'mm')
        (_el2, self.elbow_t)     = self._slider('è‚‰åš t',        3.5,  1.0,  15.0, 0.5, 'mm')
        (_el3, self.elbow_r)     = self._slider('æ›²ç‡åŠå¾„ R',    60.0, 20.0, 200.0, 5.0, 'mm')
        (_el4, self.elbow_angle) = self._slider('æ›²ãŒã‚Šè§’åº¦ Î¸',  90.0, 15.0, 180.0, 5.0, 'Â°')
        (_el5, self.elbow_ext)   = self._slider('ç›´ç®¡å»¶é•·',       20.0,  0.0,  80.0, 5.0, 'mm')
        self._rows = [_el1, _el2, _el3, _el4, _el5]
        self._btn = w.Button(description='â–¶ ç¶™æ‰‹ã‚’ç”Ÿæˆ', button_style='primary',
                             layout=w.Layout(width='150px', margin='8px 0'))
        self._btn.on_click(self._on_click)

    def _on_click(self, b: w.Button) -> None:
        self._btn.disabled = True
        self._btn.description = 'å®Ÿè¡Œä¸­...'
        self._run('ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹')
        self._btn.disabled = False
        self._btn.description = 'â–¶ ç¶™æ‰‹ã‚’ç”Ÿæˆ'

    def _build_code(self) -> str:
        od    = self.elbow_od.value
        t     = self.elbow_t.value
        R     = self.elbow_r.value
        angle = self.elbow_angle.value
        ext   = self.elbow_ext.value

        return f"""from build123d import *
import os, math
os.makedirs('output', exist_ok=True)

outer_d = {od}
wall_t  = {t}
bend_R  = {R}
angle   = {angle}
ext_len = {ext}

ro = outer_d / 2
ri = ro - wall_t

with BuildPart() as elbow:
    # â”€â”€ æ›²ãŒã‚Šéƒ¨: BuildLine ã§å††å¼§ãƒ‘ã‚¹ã‚’ä½œã‚Š sweep â”€â”€
    with BuildLine(Plane.XZ) as path_line:
        CenterArc(
            center=(bend_R, 0),
            radius=bend_R,
            start_angle=180,
            arc_size=-angle
        )

    # ã‚¹ã‚¤ãƒ¼ãƒ—æ–­é¢: ãƒ‘ã‚¹å§‹ç«¯ã®å¹³é¢ä¸Šã«ãƒªãƒ³ã‚°
    path_wire = path_line.wires()[0]
    start_pt  = path_wire.start_point()          # Vector
    start_tan = path_wire.tangent_at(0)          # å§‹ç«¯æ¥ç·šæ–¹å‘
    sweep_plane = Plane(origin=start_pt, z_dir=start_tan)

    with BuildSketch(sweep_plane) as sk_pipe:
        Circle(ro)
        Circle(ri, mode=Mode.SUBTRACT)
    sweep(path=path_wire)

    # â”€â”€ ç›´ç®¡å»¶é•·: ä¸¡ç«¯é¢ã‹ã‚‰æŠ¼ã—å‡ºã— â”€â”€
    if ext_len > 0:
        # å…¥å£å´: start_pt æ–¹å‘ã« -start_tan ã§æŠ¼ã—å‡ºã—
        with BuildSketch(Plane(origin=start_pt, z_dir=-start_tan)) as sk_in:
            Circle(ro)
            Circle(ri, mode=Mode.SUBTRACT)
        extrude(amount=ext_len)

        # å‡ºå£å´: ãƒ‘ã‚¹çµ‚ç«¯
        end_pt  = path_wire.end_point()
        end_tan = path_wire.tangent_at(1)
        with BuildSketch(Plane(origin=end_pt, z_dir=end_tan)) as sk_out:
            Circle(ro)
            Circle(ri, mode=Mode.SUBTRACT)
        extrude(amount=ext_len)

export_step(elbow.part, 'output/pipe_elbow.step')
export_stl(elbow.part,  'output/pipe_elbow.stl')
show_object = elbow
print(f'âœ… ãƒ‘ã‚¤ãƒ—ç¶™æ‰‹ phi{od}xt{t} R={R}mm {angle}deg')
print(f'   -> output/pipe_elbow.step / .stl')
"""

    def build_widget(self) -> w.VBox:
        return w.VBox([
            self._section(self.title),
            self._tip,
            *self._rows,
            self._btn,
        ])