"""
gui/tabs/samples_tab.py
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
ã‚µãƒ³ãƒ—ãƒ«ã‚¿ãƒ–ã®UIç”Ÿæˆã€‚
"""
import ipywidgets as w
from IPython.display import display, HTML
from gui.utils.code_utils import run_code
from gui.utils.viewer import _find_latest_stl, _show_viewer


SAMPLES = [
    {
        'id': 'basic_shapes',
        'label': 'â‘  åŸºæœ¬å½¢çŠ¶ï¼ˆBox / Cylinder / Sphereï¼‰',
        'desc': (
            '<b>Boxï¼ˆç›´æ–¹ä½“ï¼‰</b>: å¹…100 Ã— å¥¥è¡Œ50 Ã— é«˜ã•30 mm<br>'
            '<b>Cylinderï¼ˆå††æŸ±ï¼‰</b>: åŠå¾„25 mmã€é«˜ã•80 mm<br>'
            '<b>Sphereï¼ˆçƒï¼‰</b>: åŠå¾„20 mm<br>'
            '<span class="cad-tip">build123d ã®æœ€ã‚‚åŸºæœ¬çš„ãª3å½¢çŠ¶ã§ã™ã€‚ãã‚Œãã‚Œç‹¬ç«‹ã—ãŸ .step / .stl ã‚’å‡ºåŠ›ã—ã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

# Box
with BuildPart() as box_part:
    Box(100, 50, 30)
export_step(box_part.part, 'output/sample_box.step')
export_stl(box_part.part,  'output/sample_box.stl')
print(f'âœ… Box: ä½“ç©={box_part.part.volume:.1f} mmÂ³  â†’ output/sample_box.step / .stl')

# Cylinder
with BuildPart() as cyl_part:
    Cylinder(radius=25, height=80)
export_step(cyl_part.part, 'output/sample_cylinder.step')
export_stl(cyl_part.part,  'output/sample_cylinder.stl')
print(f'âœ… Cylinder: ä½“ç©={cyl_part.part.volume:.1f} mmÂ³  â†’ output/sample_cylinder.step / .stl')

# Sphere
with BuildPart() as sph_part:
    Sphere(radius=20)
export_step(sph_part.part, 'output/sample_sphere.step')
export_stl(sph_part.part,  'output/sample_sphere.stl')
print(f'âœ… Sphere: ä½“ç©={sph_part.part.volume:.1f} mmÂ³  â†’ output/sample_sphere.step / .stl')
""",
    },
    {
        'id': 'boolean_union',
        'label': 'â‘¡ ãƒ–ãƒ¼ãƒªã‚¢ãƒ³åˆä½“ï¼ˆUnionï¼‰',
        'desc': (
            'Boxï¼ˆ60Ã—60Ã—20 mmï¼‰ã®ä¸Šã« Cylinderï¼ˆåŠå¾„15 mmã€é«˜ã•40 mmï¼‰ã‚’åˆä½“ã•ã›ãŸå½¢çŠ¶ã€‚<br>'
            '<b>mode=Mode.ADD</b>ï¼ˆãƒ‡ãƒ•ã‚©ãƒ«ãƒˆï¼‰ã§è‡ªå‹•çš„ã«åˆä½“ã•ã‚Œã¾ã™ã€‚<br>'
            '<span class="cad-tip">è¤‡æ•°ã®å½¢çŠ¶ã‚’åŒã˜ BuildPart ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆå†…ã«ç½®ãã ã‘ã§ Union ã«ãªã‚Šã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as union_part:
    Box(60, 60, 20)
    Cylinder(radius=15, height=40)

export_step(union_part.part, 'output/sample_union.step')
export_stl(union_part.part,  'output/sample_union.stl')
print(f'âœ… Union åˆä½“: ä½“ç©={union_part.part.volume:.1f} mmÂ³  â†’ output/sample_union.step / .stl')
""",
    },
    {
        'id': 'boolean_subtract',
        'label': 'â‘¢ ãƒ–ãƒ¼ãƒªã‚¢ãƒ³å¼•ãç®—ï¼ˆSubtract / ç©´ã‚ãï¼‰',
        'desc': (
            'Boxï¼ˆ80Ã—80Ã—30 mmï¼‰ã®ä¸­å¤®ã« Cylinderï¼ˆåŠå¾„20 mmï¼‰ã§è²«é€šç©´ã‚’é–‹ã‘ãŸå½¢çŠ¶ã€‚<br>'
            '<b>mode=Mode.SUBTRACT</b> ã‚’æŒ‡å®šã™ã‚‹ã“ã¨ã§å¼•ãç®—ã«ãªã‚Šã¾ã™ã€‚<br>'
            '<span class="cad-tip">ç©´ãƒ»æºãƒ»åˆ‡ã‚Šæ¬ ãã¯ã™ã¹ã¦ã“ã®ãƒ‘ã‚¿ãƒ¼ãƒ³ã§ä½œã‚Œã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as hole_part:
    Box(80, 80, 30)
    with Locations((0, 0, 0)):
        Cylinder(radius=20, height=30, mode=Mode.SUBTRACT)

export_step(hole_part.part, 'output/sample_subtract.step')
export_stl(hole_part.part,  'output/sample_subtract.stl')
print(f'âœ… Subtract ç©´ã‚ã: ä½“ç©={hole_part.part.volume:.1f} mmÂ³  â†’ output/sample_subtract.step / .stl')
""",
    },
    {
        'id': 'bolt_plate',
        'label': 'â‘£ ãƒœãƒ«ãƒˆç©´ãƒ‘ã‚¿ãƒ¼ãƒ³ï¼ˆGridLocationsï¼‰',
        'desc': (
            'Boxï¼ˆ100Ã—100Ã—15 mmï¼‰ã®å››éš…ã«ãƒœãƒ«ãƒˆç©´ï¼ˆÏ†10 mmã€70 mmãƒ”ãƒƒãƒï¼‰ã‚’é…ç½®ã€‚<br>'
            '<b>GridLocations</b> ã§å‡ç­‰ã‚°ãƒªãƒƒãƒ‰ã«ç©´ã‚’è‡ªå‹•é…ç½®ã—ã¾ã™ã€‚<br>'
            '<span class="cad-tip">PolarLocationsï¼ˆå††å‘¨å‡ç­‰é…ç½®ï¼‰ã¨çµ„ã¿åˆã‚ã›ã‚‹ã¨æ©Ÿæ¢°éƒ¨å“ã«å¿œç”¨ã§ãã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as bolt_plate:
    Box(100, 100, 15)
    with GridLocations(70, 70, 2, 2):
        Cylinder(radius=5, height=15, mode=Mode.SUBTRACT)

export_step(bolt_plate.part, 'output/sample_bolt_plate.step')
export_stl(bolt_plate.part,  'output/sample_bolt_plate.stl')
print(f'âœ… ãƒœãƒ«ãƒˆç©´ãƒ—ãƒ¬ãƒ¼ãƒˆ: ä½“ç©={bolt_plate.part.volume:.1f} mmÂ³  â†’ output/sample_bolt_plate.step / .stl')
""",
    },
    {
        'id': 'fillet_chamfer',
        'label': 'â‘¤ ãƒ•ã‚£ãƒ¬ãƒƒãƒˆãƒ»é¢å–ã‚Šï¼ˆfillet / chamferï¼‰',
        'desc': (
            '<b>ãƒ•ã‚£ãƒ¬ãƒƒãƒˆï¼ˆR5ï¼‰</b>: Boxï¼ˆ80Ã—60Ã—25 mmï¼‰ã®ã™ã¹ã¦ã®ã‚¨ãƒƒã‚¸ã‚’ä¸¸ã‚ã‚‹ã€‚<br>'
            '<b>é¢å–ã‚Šï¼ˆC3ï¼‰</b>: åŒå½¢çŠ¶ã®ã‚¨ãƒƒã‚¸ã‚’C3ã§é¢å–ã‚Šã€‚<br>'
            '<span class="cad-tip">fillet / chamfer ã¯ã‚°ãƒ­ãƒ¼ãƒãƒ«é–¢æ•°ã¨ã—ã¦ã€å½¢çŠ¶ç¢ºå®šå¾Œã«å‘¼ã³ã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

with BuildPart() as fillet_part:
    Box(80, 60, 25)
    fillet(fillet_part.edges(), radius=5)
export_step(fillet_part.part, 'output/sample_fillet.step')
export_stl(fillet_part.part,  'output/sample_fillet.stl')
print(f'âœ… ãƒ•ã‚£ãƒ¬ãƒƒãƒˆ R5: ä½“ç©={fillet_part.part.volume:.1f} mmÂ³  â†’ output/sample_fillet.step / .stl')

with BuildPart() as chamfer_part:
    Box(80, 60, 25)
    chamfer(chamfer_part.edges(), length=3)
export_step(chamfer_part.part, 'output/sample_chamfer.step')
export_stl(chamfer_part.part,  'output/sample_chamfer.stl')
print(f'âœ… é¢å–ã‚Š C3: ä½“ç©={chamfer_part.part.volume:.1f} mmÂ³  â†’ output/sample_chamfer.step / .stl')
""",
    },
    {
        'id': 'flange_shaft',
        'label': 'â‘¥ æ©Ÿæ¢°éƒ¨å“ï¼šãƒ•ãƒ©ãƒ³ã‚¸ä»˜ãã‚·ãƒ£ãƒ•ãƒˆ',
        'desc': (
            'ã‚·ãƒ£ãƒ•ãƒˆå¾„ Ï†30 mmã€é•·ã• 120 mm ã«<br>'
            'ãƒ•ãƒ©ãƒ³ã‚¸ï¼ˆÏ†80 mmã€åšã• 15 mmï¼‰ã‚’åˆä½“ã—ã€ãƒœãƒ«ãƒˆç©´ 4Ã—Ï†10 mmï¼ˆPCD Ï†60 mmï¼‰ä»˜ãã€‚<br>'
            'ã‚·ãƒ£ãƒ•ãƒˆæ ¹å…ƒã« R3 ãƒ•ã‚£ãƒ¬ãƒƒãƒˆã€‚<br>'
            '<span class="cad-tip">LLM ãŒç”Ÿæˆã™ã‚‹ã‚³ãƒ¼ãƒ‰ã®å…¸å‹çš„ãªä¾‹ã§ã™ã€‚ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ã‚’å¤‰ãˆã¦å¿œç”¨ã§ãã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

shaft_diameter   = 30
shaft_length     = 120
flange_diameter  = 80
flange_thickness = 15
bolt_hole_dia    = 10
bolt_pcd         = 60
n_bolts          = 4
fillet_r         = 3

with BuildPart() as flange_shaft:
    Cylinder(radius=shaft_diameter/2, height=shaft_length)
    with Locations((0, 0, -shaft_length/2 + flange_thickness/2)):
        Cylinder(radius=flange_diameter/2, height=flange_thickness)
    with PolarLocations(bolt_pcd/2, n_bolts):
        Cylinder(radius=bolt_hole_dia/2, height=flange_thickness, mode=Mode.SUBTRACT)
    fillet(
        flange_shaft.edges().filter_by_position(
            Axis.Z,
            -shaft_length/2 + flange_thickness,
            -shaft_length/2 + flange_thickness + 1
        ),
        radius=fillet_r
    )

export_step(flange_shaft.part, 'output/sample_flange_shaft.step')
export_stl(flange_shaft.part,  'output/sample_flange_shaft.stl')
print(f'âœ… ãƒ•ãƒ©ãƒ³ã‚¸ä»˜ãã‚·ãƒ£ãƒ•ãƒˆ: ä½“ç©={flange_shaft.part.volume:.1f} mmÂ³')
print(f'   ã‚·ãƒ£ãƒ•ãƒˆå¾„: {shaft_diameter}mm, é•·ã•: {shaft_length}mm')
print(f'   ãƒ•ãƒ©ãƒ³ã‚¸å¾„: {flange_diameter}mm, ãƒœãƒ«ãƒˆç©´: {n_bolts}Ã—Ï†{bolt_hole_dia}mm')
print(f'   â†’ output/sample_flange_shaft.step / .stl')
""",
    },
    {
        'id': 'l_bracket',
        'label': 'â‘¦ æ©Ÿæ¢°éƒ¨å“ï¼šLãƒ–ãƒ©ã‚±ãƒƒãƒˆ',
        'desc': (
            'å¹…60 mmã€é«˜ã•80 mmã€å¥¥è¡Œã50 mmã€æ¿åš8 mm ã® L å­—ãƒ–ãƒ©ã‚±ãƒƒãƒˆã€‚<br>'
            'ç¸¦æ¿ã¨æ¨ªæ¿ã‚’ Union ã§åˆä½“ã—ã€æ¥åˆã‚¨ãƒƒã‚¸ã« R5 ãƒ•ã‚£ãƒ¬ãƒƒãƒˆã€‚<br>'
            '<span class="cad-tip">Locations ã§é…ç½®ã—ãŸ Box ã‚’ Union ã™ã‚‹ã“ã¨ã§ L å­—ãƒ»T å­—å½¢çŠ¶ã‚’ä½œã‚Œã¾ã™ã€‚</span>'
        ),
        'code': """\
from build123d import *
import os
os.makedirs('output', exist_ok=True)

width     = 60
height    = 80
depth     = 50
thickness = 8

with BuildPart() as l_bracket:
    Box(thickness, width, height)
    with Locations((depth/2, 0, -height/2 + thickness/2)):
        Box(depth, width, thickness)
    fillet(l_bracket.edges().filter_by_position(Axis.X, 0, 1), radius=5)

export_step(l_bracket.part, 'output/sample_l_bracket.step')
export_stl(l_bracket.part,  'output/sample_l_bracket.stl')
print(f'âœ… Lãƒ–ãƒ©ã‚±ãƒƒãƒˆ: ä½“ç©={l_bracket.part.volume:.1f} mmÂ³')
print(f'   å¹…:{width}mm é«˜ã•:{height}mm å¥¥è¡Œã:{depth}mm æ¿åš:{thickness}mm')
print(f'   â†’ output/sample_l_bracket.step / .stl')
""",
    },
]


def create_samples_tab() -> w.VBox:
    """ã‚µãƒ³ãƒ—ãƒ«ã‚¿ãƒ–ã®UIã‚’è¿”ã™ã€‚"""
    sample_log_out    = w.Output()
    sample_code_out   = w.Output()
    sample_viewer_out = w.Output()

    def _run_sample(code: str, label: str) -> None:
        sample_log_out.clear_output()
        sample_code_out.clear_output()
        sample_viewer_out.clear_output()
        with sample_code_out:
            display(HTML(f'<div class="cad-code">{code}</div>'))
        with sample_log_out:
            print(f'â–¶ {label} ã‚’å®Ÿè¡Œä¸­...')
        ok, err = run_code(code)
        if ok:
            with sample_log_out:
                print('âœ… ç”Ÿæˆå®Œäº†ï¼  output/ ãƒ•ã‚©ãƒ«ãƒ€ã‚’ç¢ºèªã—ã¦ãã ã•ã„ã€‚')
            stl = _find_latest_stl(code)
            if stl:
                _show_viewer(stl, sample_viewer_out)
        else:
            with sample_log_out:
                print(f'âŒ ã‚¨ãƒ©ãƒ¼:\n{err}')

    def _make_sample_row(s: dict) -> w.HBox:
        btn = w.Button(description='â–¶ ç”Ÿæˆ', button_style='success',
                       layout=w.Layout(width='90px', height='36px'))
        desc_html = w.HTML(
            f'<div style="font-size:13px;font-weight:600;margin-bottom:3px">{s["label"]}</div>'
            f'<div style="font-size:12px;line-height:1.6">{s["desc"]}</div>'
        )
        row = w.HBox([btn, desc_html], layout=w.Layout(
            padding='10px', margin='4px 0', border='1px solid #dee2e6',
            border_radius='6px', align_items='flex-start', gap='14px'))

        def on_click(b, _code=s['code'], _label=s['label']):
            btn.disabled = True; btn.description = 'å®Ÿè¡Œä¸­...'
            _run_sample(_code, _label)
            btn.disabled = False; btn.description = 'â–¶ ç”Ÿæˆ'

        btn.on_click(on_click)
        return row

    sample_rows = [_make_sample_row(s) for s in SAMPLES]

    return w.VBox([
        w.HTML('<div style="font-size:13px;color:#555;margin-bottom:8px">'
               'â–¶ ç”Ÿæˆ ãƒœã‚¿ãƒ³ã‚’æŠ¼ã™ã¨ã‚³ãƒ¼ãƒ‰ãŒè¡¨ç¤ºã•ã‚Œã€STEP/STL ãŒ <code>output/</code> ã«ä¿å­˜ã•ã‚Œã¾ã™ã€‚</div>'),
        *sample_rows,
        w.HTML('<hr style="margin:10px 0"><b>å®Ÿè¡Œãƒ­ã‚°</b>'),
        sample_log_out,
        w.HTML('<b>ğŸ–¥ï¸ 3Dãƒ“ãƒ¥ãƒ¼ã‚¢</b>'),
        sample_viewer_out,
        w.HTML('<b>å®Ÿè¡Œã‚³ãƒ¼ãƒ‰</b>'),
        sample_code_out,
    ], layout=w.Layout(padding='10px'))
